helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/config-ConfigMap.yaml

Updated prow logo

---

eks-distro-base/check_update.sh
eks-distro-base/install_gh.sh

Fix variable names in script, move GH installation to bin/

Fix scripts to get periodic running

---

projects/gomods/athens/Makefile
projects/gomods/athens/upload-athens-artifacts.sh

Build and uplaod Athens artifacts

---

projects/gomods/athens/upload-athens-artifacts.sh

Upload athens image and install toolchain

---

projects/gomods/athens/Makefile
projects/gomods/athens/upload-athens-artifacts.sh

Set the path variable to use helm

---

projects/gomods/athens/Makefile

Store athens image in gomods/athens ecr repo

---

helm-charts/stable/amazon-eks-pod-identity-webhook/templates/_helpers.tpl

Adding an app label to keep it consistent for testing

Add app selector to webhook

---

builder-base/README.md

Generate builder image

---

pr-scripts/create_pr.sh

Added target remote branch to git push command.

Fix git push command for PR creation

---

OWNERS

Add the rest of the team to reviewers

Add team to owners file

---

builder-base/install.sh

Adding a comment, also want to retrigger builder-base builds and update image tags in prow job repo.

Add comment to setupgo function

---

projects/aws/eks-charts/aws-for-fluent-bit/Makefile

Add helm chart for aws-for-fluent-bit

---

OWNERS

Add rest of team to approvers.

Add rest of team members to approvers

---

eks-distro-base/Makefile

Fix Makefile for humans

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/config-ConfigMap.yaml

Set squash as default method for Prow merges

---

release/Makefile
release/api/v1alpha1/release.go
release/api/v1alpha1/releasechannel.go
release/cmd/release.go
release/config/crds/distro.eks.amazonaws.com_releasechannels.yaml
release/config/crds/distro.eks.amazonaws.com_releases.yaml
release/pkg/assets_attacher.go
release/pkg/assets_authenticator.go
release/pkg/assets_cni.go
release/pkg/assets_coredns.go
release/pkg/assets_etcd.go
release/pkg/assets_k8s.go
release/pkg/assets_livenessprobe.go
release/pkg/assets_metricsserver.go
release/pkg/assets_provisioner.go
release/pkg/assets_registrar.go
release/pkg/assets_resizer.go
release/pkg/assets_snapshotter.go

Use the release number as a string

Release number as string

---

builder-base/install.sh

Installs using release tag instead of commit hash

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/config-ConfigMap.yaml
helm-charts/stable/prow-control-plane/templates/plugins-ConfigMap.yaml

Configure support for empty repos in `prow-control-plane` helm chart

Configure support for empty repos

---

builder-base/golang-checksum
builder-base/install.sh

Our golang versions have gotten a bit behind.

update to latest patch release for each golang minor

---

generate-attribution/generate-attribution-file.js

Handle dependencies that get pulled in from a parent.  This happened with clsuter-api projects [here](https://github.com/aws/modelrocket-build-tooling/pull/41/files)

better handling of go.mod replace calls for attribution files

---

builder-base/README.md
eks-distro-base/README.md

This will also trigger the base image builds and pushes.

Add reference to public ECR base image repos in respective READMEs

---

builder-base/Makefile
scripts/setup_public_ecr_push.sh

Ensuring that env variables are set as expected.

Perform ecr-setup step in presubmit

---

scripts/setup_public_ecr_push.sh

We set these as env vars in the postsubmits so we don't need them here.

Remove unnecessary exports from script

---

scripts/setup_public_ecr_push.sh

Validate proper configuration of role_arn's

Check if ROLE_ARNs are set properly in script

---

scripts/setup_public_ecr_push.sh

Add comment to clarify purpose of creating a config file.

Add comment to ECR setup script

---

builder-base/update_base_image.sh

Since the image repo name changed, we need to fix the search regex in this script.

Fix regex for proper sed replacement

---

pr-scripts/builder_base_pr_body

Clarify that the same image tag will also be used for Codebuild so that we have auditability.

Improvde PR description for builder-base tag update

---

release/config/1-20/1-20.yaml

Added 1-20 release channel

---

builder-base/Makefile
eks-distro-base/Makefile
projects/aws/amazon-eks-pod-identity-webhook/Makefile
projects/gomods/athens/Makefile
projects/infinityworks/github-exporter/Makefile
projects/prometheus/alertmanager/Makefile
projects/prometheus/prometheus/Makefile
scripts/buildkit_check.sh

Run a script to check if buildkit daemon is running before invoking buildkit client

Add script to check if buildkit daemon is running

---

projects/infinityworks/github-exporter/Makefile

Fix typo in postsubmit make target

---

builder-base/Makefile
builder-base/install.sh
builder-base/update_base_image.sh
eks-distro-base/Makefile
eks-distro-base/check_update.sh
eks-distro-base/update_base_image.sh
pr-scripts/create_pr.sh
pr-scripts/eks_distro_base_pr_body

/hold
The PR body for the eks-distro-base tag update PR should also contain the packages updated.

Add updated yum packages to PR body

---

README.md
generate-attribution/README.md
helm-charts/stable/amazon-eks-pod-identity-webhook/README.md
projects/prometheus/alertmanager/README.md

Fixed typos in some of the Docs

---

release/config/1-21/1-21.yaml

1-21 release runbook step 4:
https://github.com/aws/eks-distro/blob/main/docs/contents/runbook.md

added 1-21 channel to release tooling

---

generate-attribution/generate-attribution-file.js

Passing auth token in header so that rate limiting doesn't occur.

Add auth header with github token for reading licenses

---

eks-distro-base/Makefile

N/A
Fixes postsubmit image bulid

Fixed postsubmit image build

---

pr-scripts/update_local_branch.sh

N/A
Give credit where credit is due

Bots deserve commit histories too

---

projects/grafana/helm-charts/Makefile

Changing Grafana helm-chart version.

Updating Grafana helm-chart version

---

eks-distro-base/check_update.sh

Fix base image name in check-update script

---

generate-attribution/generate-attribution-file.js

Sometimes the return content doesnt have the attribution we are looking for.

attribution: handling missing meta tag for package url

---

builder-base/update_base_image.sh
eks-distro-base/update_base_image.sh
pr-scripts/update_local_branch.sh

Add tag update automation to EKS Anywhere build tooling and Prowjob repos
/hold

Add tag update automation for eks-anywhere repos

---

pr-scripts/update_local_branch.sh

Modified the conditional to perform checkout from `upstream/main` in postsubmits.

Refactor git config to support postsubmits

---

pr-scripts/update_image_tag.sh

The automated PR is created from a second clone of the repo.  This copies the new package files to the other repo similar to when it updates the tag_files.

eks-distro: fix minimal packages update during periodic

---

builder-base/install.sh

builder: fix go-licenses by installing later in the process

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/config-ConfigMap.yaml
helm-charts/stable/prow-control-plane/templates/plugins-ConfigMap.yaml

* Retain Prowjobs for 30 days instead of a week
* Add more useful Prow plugins

Retain Prowjobs for longer

---

eks-distro-base/Makefile

base: call proper make target for minimal images

---

builder-base/install.sh

QEMU emulation for ARM builder-base fails during this step leading to segmentation faults, hence building it for just amd64. It will possibly be added later after root-causing and fixing it.

Build multiple Golang versions only for amd64 version

---

builder-base/docker.sh

These functions will be consumed by sourcing this script.

Remove function calls in Docker script

---

builder-base/install.sh

Adding symlinks from initial Go installation bin directory to `GOPATH/go<major.minor>/bin` to maintain parity with existing scripts.

Symlink Go binaries to versioned bin folder in GOPATH

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/config/install.sh
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/install-ClusterRole.yaml

pod-id: workaround upgrade issues with mwc and old CSRs

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/config/install.sh
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/install-ClusterRole.yaml

pod-webhook: add new cluster role perm for signing key from webhook

---

projects/grafana/helm-charts/Makefile

Bump Grafana helm chart version to 6.18.2

---

builder-base/install.sh

add golang 1.17 to arm image for source-controller

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/cherrypicker-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/cherrypicker-Service.yaml
helm-charts/stable/prow-control-plane/templates/plugins-ConfigMap.yaml
helm-charts/stable/prow-control-plane/values.yaml

Add cherrypicker plugin to prow

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/cherrypicker-Deployment.yaml

Just change the token so it uses the PR bot instead of the eks-distro bot

Use PR bot for cherrypicker plugin

---

eks-distro-base/Makefile
eks-distro-base/check_update.sh

eks-distro-base: check proper image tag for 2022 builds

---

EKS_DISTRO_TAG_FILE.yaml
eks-distro-base/Dockerfile.minimal-base
eks-distro-base/Dockerfile.minimal-base-docker-client
eks-distro-base/Dockerfile.minimal-base-kind
eks-distro-base/Makefile
eks-distro-base/check_update.sh
eks-distro-base/scripts/clean_install
eks-distro-base/scripts/enable_docker_install
eks-distro-base/update_base_image.sh

eks-distro-base: new base tag yaml file format support

---

pr-scripts/create_pr.sh

This prevents them from being merged inadvertently.

Add hold label to bot-authored pull requests

---

eks-distro-base/Dockerfile.minimal-base-git
eks-distro-base/Makefile

- Make sure and actually git add new base tag yaml file
- Change 2022 git variant to pull libssh/git from yum since the versions are fairly up to date now.

git add the new file

---

EKS_DISTRO_TAG_FILE.yaml

force image tag update job to run

---

EKS_DISTRO_TAG_FILE.yaml
eks-distro-base-updates/update_packages-eks-distro-minimal-base-git
eks-distro-base/check_update.sh
pr-scripts/create_pr.sh

We are going to keep the last updated packages file in the repo so we can put in the PR messages when opening PRs in other repos.

check in updates to support showing in PR descriptions

---

builder-base/install.sh

This will be useful in scripts.

Add patch utility to builder-base

---

builder-base/amazon-ecr-cred-helper-arm64-checksum
eks-distro-base/Makefile

eks-distro-base: fix periodic failing on git add

---

helm-charts/scripts/install-toolchain.sh
helm-charts/stable/amazon-eks-pod-identity-webhook/config/install.sh

Update kubectl to use the latest

Update kubectl binary to 1.22

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/plugins-ConfigMap.yaml

Disable blunderbuss prow plugin by default

---

helm-charts/scripts/verify-version.sh

Patch folder needs to be added to the diff targets, not replace them.

Use proper git diff target in Helm version check

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/deck-Ingress.yaml

This was accidentally removed in the refactor

Add Deck ingress template

---

EKS_DISTRO_TAG_FILE.yaml

2022 periodic timed out, updating tags

---

eks-distro-base/Makefile

distro-base: checkout local branch before checking for PRs

---

eks-distro-base/Makefile

I forgot to update the create-pr and update targets based on my changes in my last pr.  This should fix the update flow and updating the tag file for the standard image tag.

distro-base: fix create-pr and update targets

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/values.yaml

Add builder-base tag file to config updater list.

Add builder-base tag file to config updater list

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/plugins-ConfigMap.yaml
helm-charts/stable/prow-control-plane/values.yaml

* Require approval even when author is an approver
* Github PR approvals are equivalent to /lgtm

Configure eks-anywhere PR reviews

---

builder-base/install.sh

builder: bump golang to 1.18.1 and 1.17.9

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/values.yaml

Use same PR config for all eks-d and eks-a repos

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/config-ConfigMap.yaml

* Overrides [defaults](https://github.com/kubernetes/test-infra/blob/41dbe2e1e4ed6e324d8f40eca520453a8ab2dab2/prow/config/prow-config-documented.yaml#L978-L988), which were not enough time

Increased default timeout of pods for plank

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/values.yaml

Bumped iam auth and chart versions

---

builder-base/install.sh

builder-base: install go-licenses to different folders

---

builder-base/update_base_image.sh
pr-scripts/create_pr.sh

Adding this file to the automated PR workflow.

Make script update the builder-base tag file in EKS Anywhere Prowjobs repo too

---

release/config/1-23/1-23.yaml

Added 1-23 release config

---

builder-base/install.sh

Upgrades go to 1.18.2 and 1.17.10

---

builder-base/install.sh

update go-licenses to 1.2.1

---

eks-distro-base/check_update.sh

distro-base: Fixes security update check for extras packages 

---

builder-base/install.sh

So that it is accessible by all users.

Copy Tuftool to top-level bin directory

---

eks-distro-base/Makefile

distro-base: fixes python check-updating

---

eks-distro-base/scripts/eks-d-common

Ignores objdump failures

---

release/config/1-24/1-24.yaml

Added release config for 1-24

---

projects/kubernetes/kops/Makefile

bump kOps version

---

projects/kubernetes/kops/Makefile

Fixes git tag path for kops build

---

projects/kubernetes/kops/Makefile

ensure public-acl flag is set for uploads

---

generate-attribution/generate-attribution-file.js

See if this helps run away attribution jobs

Adds timeout to attribution https requests

---

builder-base/install.sh

https://github.com/aws/eks-distro-build-tooling/issues/479
Bumps Go 1.17.3

Bump 1.17.12 to 1.17.3

---

projects/golang/go/1.15/patches/0001-go-1.15.15-eks-archive-zip-prevent-preallocat.patch
projects/golang/go/1.15/patches/0002-go-1.15.15-eks-debug-macho-fail-on-invalid-dy.patch
projects/golang/go/1.15/patches/0003-go-1.15.15-eks-syscall-fix-ForkLock-spurious-close-0.patch

fix spacing in headers...also, trigger the new presubmits :)

normalize spacing in patch headers

---

projects/golang/go/1.17/patches/0102-cmd-go-disable-Google-s-proxy-and-sumdb.patch

When using git am to patch there was an error. I regenerated patch for 1.17.

Regenerate patch for 1.17

---

projects/golang/go/Makefile

removed duplicated command and fix spacing

---

projects/golang/go/1.16/README.md

trigger postsubmit

---

projects/golang/go/Makefile
projects/golang/go/scripts/release_s3_configuration.sh

https://github.com/aws/eks-distro-internal/issues/241
Set up the AWS CLI config in the Go prod-release post-submits container as part of the release process.

set up aws config in golang tooling prod release post-submit

---

projects/golang/go/1.15/README.md
projects/golang/go/1.16/README.md
projects/golang/go/1.17/README.md
projects/golang/go/1.18/README.md

Add basic readmes with prow build status badges to each Go version

add and update readmes with build badges

---

builder-base/Makefile
scripts/buildkit.sh
scripts/setup_buildx.sh

Uses buildx for builder-base pre and post submit

---

eks-distro-base/Makefile

Switches to buildx for eks-distro-base image builds

---

helm-charts/stable/prow-data-plane/Chart.yaml
helm-charts/stable/prow-data-plane/templates/buildkit-orchestration-Role.yaml

Tweaks buildkit roles and bindings

---

builder-base/Dockerfile
builder-base/Makefile
builder-base/scripts/install_ansible.sh
builder-base/scripts/install_go_licenses.sh
builder-base/scripts/validate_components.sh

Add back default go-licenses symlink

Adds back default go-licenses symlink

---

EKS_DISTRO_TAG_FILE.yaml
eks-distro-base/check_update.sh

Add remaining compiler names and fix check update

---

eks-distro-base/check_update.sh

Fixes check update for standard base

---

eks-distro-base/Dockerfile.minimal-base-compiler

Copy common scripts in compiler base builder

---

eks-distro-base/check_update.sh

Al22 organizes packages into {releasever}s so with every package update you could pin to a specific set of packages. 
This seems like a cool approach, but for us this is not exactly what we want since we are trying to minimize the number of updates we are actually doing to these images by only updating when there are security updates. They recently added a releasever latest to allow checking, and updating, across releasever without having to do a full system update.  This allows us to follow a similar approach as with al2 for checking for updates

Changes al22 check update to use --security and latest

---

EKS_DISTRO_TAG_FILE.yaml
eks-distro-base/Dockerfile.minimal-base-compiler
eks-distro-base/Dockerfile.minimal-base-golang
eks-distro-base/scripts/install_golang
eks-distro-base/tests/run_tests.sh

Addes which to the base compiler, this feels reasonable? Ads yum ovl plugin to fix issues in fargate when installing additional packages.

Adds rpms to rpmdb for golang builds

---

projects/golang/go/Makefile

Switches to using go provided by eks-d minimal images

---

projects/golang/go/Makefile

clean up make file

---

projects/golang/go/Makefile

fix typo in EKS Go makefile

---

projects/golang/go/development/docs/eks_go_patching_runbook.md

Updates runbook to make the order more explicit around updates.

Update runbook to make updating to the new patch versions more explicit

---

projects/golang/go/Makefile

we were running into space issues during image build without this

clean multi-platform std lib installs after each test run

---

release/config/1-25/1-25.yaml

Related to https://github.com/aws/eks-distro/issues/1472
Added release config for 1.25

Added release config for 1.25

---

eks-distro-base-updates/update_packages-eks-distro-minimal-base-python

Removes old python updates file

---

scripts/setup_buildx.sh

The trap cleanup seems to work pretty well, there are only 2 left over right now that are from crashed jobs, but just to have a fail safe for these cases.  This approach is similar to what we do in eks-distro [postsubmits](https://github.com/aws/eks-distro/blob/main/development/kops/run_all.sh#L40) to clean up potentially old clusters that werent properly cleaned

Cleans older buildkit deployments left from failed jobs

---

projects/golang/go/Makefile

test change to makefile

---

projects/golang/go/Makefile

add some clarifying comments to EKS Go makefile

---

helm-charts/stable/binfmt/Chart.yaml
helm-charts/stable/binfmt/values.yaml

This binfmt image is quite outdated, so bumping it.

Bump up binfmt image to latest

---

builder-base/Makefile
builder-base/scripts/download_golang.sh
builder-base/scripts/install_golang.sh

Reuse golang rpm downloads instead of redownloading

---

pr-scripts/create_pr.sh
pr-scripts/open_pr_check.sh

I have no idea what i tested and how when i first made this change, but this tweaks the cli call just a bit to better utilize the newer version of the cli and should be correct now...

Fixes open pr check

---

pr-scripts/create_pr.sh

Fixes bad condition when opening PR

---

release/config/1-26/1-26.yaml

Added release channel for 1.26

---

projects/golang/go/development/scripts/patches/apply_patches.sh
projects/golang/go/development/scripts/patches/lib/patch.sh

Go patching script

---

projects/golang/go/Makefile

*Description of changes:* To make sure clean checksum build

Add Logs to verify checksums for ARM and AMD Prod postsubmit

---

tools/eksDistroBuildToolingOpsTools/cmd/eksDistroOpsProwPlugin/server.go

To test the ops tool without disrupting the flow of issues in the main fork. We will have to cut the ticket to the aws fork to trigger the tool

Ops tool test changes

---

helm-charts/stable/prow-control-plane/values.yaml

Once #829 merges and postsubmits complete. Merge this to trigger new deployment of plugin with updated version for testing.

Update Plugin Version in helm chart

---

helm-charts/stable/prow-control-plane/values.yaml

Change the image version for iam auth

Update iam auth version for Prow

---

helm-charts/stable/prow-control-plane/Chart.yaml

Update chart version to trigger CDK to redeploy.

update chart version

---

helm-charts/stable/prow-control-plane/values.yaml

Reverts aws/eks-distro-build-tooling#833

Revert "Update iam auth version for Prow"

---

projects/golang/go/README.md

Include golang 1.20 in golang readme

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/values.yaml

Change the plugin version to the new proxyhost and fixed return issue plugin. Also helm chart version to redeploy the plugin.

Update the plugin version and the helm chart version

---

builder-base/Makefile
builder-base/README.md

Trigger a builder-base post-submit with minor changes

minor change to trigger post-submit

---

eks-distro-base/README.md

Updates to Readme to clarify update flow

---

projects/golang/go/1.15/patches/0025-go-1.15.15-eks-path-filepath-do-not-clean-relative-path.patch
projects/golang/go/1.15/patches/0026-go-1.15.15-eks-update-bundled-golang-org.patch
projects/golang/go/1.15/patches/0027-go-1.15.15-eks-replace-all-usages-of-BytesOrPanic.patch
projects/golang/go/1.15/patches/0028-go-1.15.15-eks-multipart-limit-memory-inode-consumption.patch
projects/golang/go/1.15/rpmbuild/SPECS/golang.spec

Generate Patches for Go1.15.15

---

builder-base/Makefile

this was leading to the builder-base post-submits to not create a PR

fix typo in makefile

---

.github/workflows/base-image-pr-notifier.yml

Workflow to notify new PRs for Base image updates

Add workflow to notify new base image updates

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/deck-Ingress.yaml

Update the api in Deck to a the new version supported in K8s 1.22+.

Update api to supported version for Deck

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/deck-Ingress.yaml

This was inadvertently removed in #896.

Re-add removed name field in Deck Ingress

---

projects/golang/go/1.15/patches/0025-go-1.15.15-eks-path-filepath-do-not-clean-relative-path.patch
projects/golang/go/1.15/patches/0026-go-1.15.15-eks-update-bundled-golang-org.patch
projects/golang/go/1.15/patches/0027-go-1.15.15-eks-replace-all-usages-of-BytesOrPanic.patch
projects/golang/go/1.15/patches/0028-go-1.15.15-eks-multipart-limit-memory-inode-consumption.patch
projects/golang/go/1.16/patches/0026-go-1.16.15-eks-update-bundled-golang-org.patch
projects/golang/go/1.16/patches/0027-go-1.16.15-eks-path-filepath-do-not-clean-relative-path.patch
projects/golang/go/1.16/patches/0028-go-1.16.15-eks-multipart-limit-memory-inode-consumption.patch
projects/golang/go/1.16/patches/0029-go-1.16.15-eks-replace-all-usages-of-BytesOrPanic.patch
projects/golang/go/1.18/patches/0001-go-1.18.10-eks-update-bundled-golang.org.patch
projects/golang/go/1.18/patches/0002-go-1.18.10-eks-replace-all-usages-of-BytesOrPanic.patch
projects/golang/go/1.18/patches/0003-go-1.18.10-eks-multipart-limit-memory-inode-consumption.patch
projects/golang/go/1.18/patches/0004-go-1.18.10-eks-path-filepath-do-not-Clean-relative-path..patch

Format EKS-Go patches for go1.15, 1.16, 1.18

---

builder-base/scripts/install_ansible.sh
builder-base/scripts/install_final.sh
eks-distro-base/scripts/install_golang

Change the remaining AL22 references to AL23.

Update AL22 to AL23 across build base scripts

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/values.yaml

To be merged after the post submits of https://github.com/aws/eks-distro-build-tooling/pull/927 are finished running. This will have the new chart include the new image pushed by the post submits.

update helmchart version and plugin version

---

projects/golang/go/development/docs/eks_go_patching_runbook.md

Update Golang patch runbook

---

release/config/1-27/1-27.yaml

Added release channel for 1.27

---

projects/golang/go/Makefile

This is currently broken due to permissions issues, removing it until we get around to fixing it.

remove image release target from prod release

---

eks-distro-base/check_update.sh
eks-distro-base/update_base_image_other_repos.sh
pr-scripts/create_pr.sh

The main change here is supporting updating al2023 tag files in other repos when new images are built. We recently started using the kind [al23](https://github.com/aws/eks-anywhere-build-tooling/blob/main/EKS_DISTRO_MINIMAL_BASE_KIND_AL2023_TAG_FILE) image in eks-a.
In addition this will also make a few cleanups regarding the PRs which are opened.
- [This](https://github.com/aws/eks-distro-build-tooling/pull/956/files#diff-f23aae0be1b89c14a671edc5e0c17b7f87131f9d29726fdcbadc7e55c0f8d774R79) should limit the times we update the packages files, which we only use to generate the PR in the other repos, to times that it actually updated, vs now they all get null'd out anytime any image is updated
- These tracking files have been moved into …

Handle updating al2023 tag files in other repos

---

builder-base/scripts/install_final.sh

Looking to build containerd for eks-a, need these 3 packages which end up being a pretty small usage increase.

Adds static packages needed to build containerd

---

projects/kubernetes/kops/Makefile
projects/kubernetes/kops/kops_artifacts_management_tools.sh

makefile changes

---

.github/workflows/docker-check.yml
builder-base/Dockerfile
eks-distro-base/Dockerfile.minimal-base-iptables
projects/golang/go/docker/debianBase/Dockerfile
tools/eksDistroBuildToolingOpsTools/docker/Dockerfile

Replace ADD with COPY in dockerfiles

---

projects/golang/go/1.17/patches/0017-go-1.17.13-eks-html-template-emit-filterFails.patch
projects/golang/go/1.17/patches/0018-go-1.17.13-eks-html-template-handle-all-JS-wh.patch
projects/golang/go/1.17/patches/0019-go-1.17.13-eks-html-template-disallow-angle-b.patch
projects/golang/go/1.17/rpmbuild/SPECS/golang.spec

Add go1.17.13 patch

---

projects/golang/go/1.16/patches/0035-go1.16.15-eks-html-template-emit-filterFails.patch
projects/golang/go/1.16/patches/0036-go1.16.15-eks-html-template-handle-all-JS-wh.patch
projects/golang/go/1.16/patches/0037-go1.16.15-eks-html-template-disallow-angle-b.patch
projects/golang/go/1.16/rpmbuild/SPECS/golang.spec

Add go1.16.15 patches

---

projects/golang/go/1.15/patches/0034-go1.15.15-eks-html-template-emit-filterFails.patch
projects/golang/go/1.15/patches/0035-go1.15.15-eks-html-template-handle-all-JS-wh.patch
projects/golang/go/1.15/patches/0036-go1.15.15-eks-html-template-disallow-angle-b.patch
projects/golang/go/1.15/rpmbuild/SPECS/golang.spec

Add go1.15.15 patches

---

pr-scripts/create_pr.sh
pr-scripts/prow_cp_pr_body
pr-scripts/prow_deck_pr_body

Improving PR titles and commit messages a bit.

Minor cleanup in PR creation script

---

release/go.mod
release/go.sum

Updated release to go 1.20

---

OWNERS

Reordered OWNERS and added new people

---

builder-base/scripts/download_golang.sh

*Issue #, if available:* [link to the issue](https://github.com/orgs/aws/projects/23/views/5?pane=issue&itemId=33341027)

Add http error check in download_golang script

---

builder-base/Makefile
builder-base/scripts/download_golang.sh

Add architecture argument for golang_download script

---

release/config/1-28/1-28.yaml

https://github.com/aws/eks-distro/issues/2206
Added 1.28 release channel 

Add 1.28 release channel

---

eks-distro-base/update_base_image_other_repos.sh

Added check for files exists

---

projects/golang/go/scripts/debian_image_release_notification.sh
projects/golang/go/scripts/eks_golang_release_notification.sh

Since we call the publish sns message in a separate script from prow jobs release, when the first script finishes it's exports are not persistent. We need to assume the correct role in the script to publish. To be safe, I even create the aws profiles again just to make sure they persist correctly.

Add the aws profiles and profile export in go sns scripts

---

projects/golang/go/scripts/debian_image_release_notification.sh
projects/golang/go/scripts/eks_golang_release_notification.sh

* Added cd to base directory
* Minor clean up unrelated to error

Golang SNS scripts bug fix

---

projects/golang/go/scripts/eks_golang_release_notification.sh

Potential golang sns fix

---

projects/golang/go/scripts/eks_golang_release_notification.sh

This reverts commit 494b47d21098f4f1c2577d92e1a10c1c17f30a0e.
Change is not needed

Revert "Potential golang sns fix (#1119)"

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/_helpers.tpl

Fix suffix typo in amazon-pod-identity-webhook helper template

---

.github/workflows/golangci-lint.yml

Updating golint github actions to use new version of go and go-lint, following go-lint [readme](https://github.com/golangci/golangci-lint-action)

Update golint github action

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Deployment.yaml

Update pod-identity-webhook cert secret path typo

---

.github/labeler.yml
.github/workflows/label.yml

Add auto labeller similar to other repos. Started with things of importance like minimal-images, builder-base, al2/2023, golang/go and the various version, etc.

Add autolabeler for various labels

---

tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/newRelease.txt
tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/readmeFmt.txt

These files are required for the future golang automation. 

Add files required for future EKS Go automation 

---

EKS_DISTRO_TAG_FILE.yaml

Trigger ip-tables image update

---

release/Makefile

Set go PATH to go1.18 for release/pkg

---

release/config/1-29/1-29.yaml

https://github.com/aws/eks-distro/issues/2555
Create release yaml for kubernetes v1.29

Create 1.29 config yaml

---

release/pkg/kube_reader.go

Add the fix for filtering `+` to the minor version.

Move replace to minor not major

---

builder-base/scripts/install_notation.sh
builder-base/scripts/validate_components.sh

Verify notation AWS Signer plugin installation during image build. 

Verify notation AWS Signer plugin installation

---

projects/golang/go/scripts/eks_golang_release_notification.sh

Updating the sns message to include the github location for more information about the artifacts location

add metadata flag with location of eks go artifacts in sns

---

eks-distro-base/Makefile

Revert changes to make update

---

builder-base/Dockerfile
projects/golang/go/build/conformanceTests/golangBuildspec.yaml

Golang 1.22 builder-base & golangBuildspec change

Golang 1.22 builder-base & golangBuildspec change

---

release/config/1-30/1-30.yaml

Add release config for 1.30

---

EKS_DISTRO_TAG_FILE.yaml

Force Rebuild IPTables with new golang release

---

projects/golang/go/1.21/rpmbuild/SPECS/golang.spec

Updated changelog to use the correct day for the commit date

Update changelog to use the correct day for the commit date

---

EKS_DISTRO_TAG_FILE.yaml

#1433 didn't null al2023 images

Trigger al2023 Builder Base EKSGo

---

builder-base/Makefile
eks-distro-base/Makefile
pr-scripts/create_pr.sh

Make targets for releasing the new versions of golang. Will be targeted by this periodic https://github.com/aws/eks-distro-prow-jobs/pull/617 to automate.

Add make targets for checking and releasing new versions of golang

---

pr-scripts/create_pr.sh

Add diff to debug pr script

---

builder-base/scripts/check_upstream_golang.sh
builder-base/scripts/download_golang.sh

Move updating checksums to checking upstream release

---

pr-scripts/create_pr.sh

Correcting the path for the `cp` directory copy commands. 
Output from local linux box.
```
cp -rf ../builder-base/checksums ~/tmp
‘../builder-base/checksums/yq-amd64-checksum’ -> ‘/home/rcrozean/tmp/checksums/yq-amd64-checksum’
‘../builder-base/checksums/go-go1.21-arm64-checksum’ -> ‘/home/rcrozean/tmp/checksums/go-go1.21-arm64-checksum’
‘../builder-base/checksums/upx-amd64-checksum’ -> ‘/home/rcrozean/tmp/checksums/upx-amd64-checksum’
‘../builder-base/checksums/notation-amd64-checksum’ -> ‘/home/rcrozean/tmp/checksums/notation-amd64-checksum’
‘../builder-base/checksums/goss-amd64-checksum’ -> ‘/home/rcrozean/tmp/checksums/goss-amd64-checksum’
‘../builder-base/checksums/oras-amd64-checksum’ -> …
```

Update verbosity for cp in golang periodic

---

projects/golang/go/Makefile
projects/golang/go/scripts/get_upstream_golang.sh

Add expected go to front of golang-debian image tag

---

release/config/1.31/1.31.yaml

*Issue https://github.com/aws/eks-distro/issues/3214, if available:*
1. Created the new 1.31 release config yaml

Created the 1.31 release config yaml

---

EKS_DISTRO_TAG_FILE.yaml

trigger builder-base update for iptables 

---

projects/golang/go/docker/debianBase/Dockerfile

update golang-debian image to build to /usr/local/go

---

projects/golang/go/scripts/get_upstream_golang.sh

hardcode checksum check to unblock 1.22.6 debian release

---

release/config/1-32/1-32.yaml

add 1-32 release config

---

eks-distro-base/Dockerfile.minimal-base-csi
eks-distro-base/Dockerfile.minimal-base-csi-ebs
eks-distro-base/Dockerfile.minimal-base-kind

Adds new dangling link for cleanup

Add new dangling link for cleanup

---

release/pkg/assets_metricsserver.go

deprecate metrics server from build tooling

---

release/pkg/assets_metricsserver.go

fix metrics-server tag in release

---

release/config/1-33/1-33.yaml

Added release config for 1.33

---

projects/kubernetes/kops/patches/0002-Remove-cloud-config.patch

Add patch to remove cloud config

---

EKS_DISTRO_TAG_FILE.yaml

Trigger rebuild for base image update for iptables. 

Trigger rebuild for iptable base image update

---

EKS_DISTRO_TAG_FILE.yaml

Updated the windows base images to null

---

scripts/buildkit.sh

Handled retry on httpReadSeeker by buidkit

---

scripts/buildkit.sh

buildkit is not returning non-zero exist code for `ERROR: httpReadSeeker:` errors, therefore, retries are not working and jobs are failing.
Eg: https://prow.eks.amazonaws.com/view/s3/prowdataclusterstack-316434458-prowbucket7c73355c-1n9f9v93wpjcm/logs/eks-distro-base-tooling-periodic-al-2023/1929795343138951168
Job after fixing retries: https://prow.eks.amazonaws.com/view/s3/prowdataclusterstack-316434458-prowbucket7c73355c-1n9f9v93wpjcm/logs/eks-distro-base-tooling-periodic-al-2023/1931054631639584768
```
Exit Code from job: 0
#32 ERROR: httpReadSeeker: failed open: content at https://public.ecr.aws/v2/eks-distro-build-tooling/golang/manifests/sha256:ae2f029167e4d11d4afd88ffe08879d24e6f635b5dbdcb04e81f402b7be7a1de not found: not found …
```

Added retry logic to buildkit job

---

projects/kubernetes/kops/patches/0001-Add-Kubernetes-1-33-compatibility-with-cloud-provider-and-cloud-config-changes.patch
projects/kubernetes/kops/patches/0002-Remove-register-schedulable-kubelet-flag-in-1.34.patch

 update 1-32 with patches require to support 1.34 k8s

---

generate-attribution/generate-attribution-file.js

make reading git tag synchronous in generate-attribution

---

OWNERS

adding nikhila2610 to OWNERS and removed Jerad and Jared

---

release/pkg/assets_kubeproxy.go

update kube-proxy crd generation to use correct tags
