helm-charts/scripts/install-toolchain.sh

Install the kubectl binary from EKS Distro CloudFront distribution instead of from Google Cloud Storage.

Modify tools install script to use EKS Distro build of kubectl

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/crier-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/deck-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/ghProxy-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/hook-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/horologium-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/kubeconfig-Secret.yaml
helm-charts/stable/prow-control-plane/templates/prow-controller-manager-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/sinker-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/statusreconciler-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/tide-Deployment.yaml

* Adds a session name to help debug which IAM role sessions are associated with which pods 
* Ensure that aws-iam-authenticator is using the regional endpiont

Set session name on prow cp pods

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/kubeconfig-Secret.yaml

Validated that regional endpoints are used if `--region` is passed. I don't know why the Go SDK doesn't respect `AWS_STS_REGIONAL_ENDPOINTS` when getting the initial AWS creds. 

Use regional endpionts for authenticator

---

builder-base/Makefile
eks-distro-base/Makefile
eks-distro-base/check_update.sh

Script fails when a command has a non-zero exit code, due to `set -e` option. Added a hack to work around this. This construct still preserves the non-zero code but does not exit the script abruptly.

Prevent script from failing due to non-zero exit code

---

helm-charts/stable/amazon-eks-pod-identity-webhook/.helmignore
helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/README.md
helm-charts/stable/amazon-eks-pod-identity-webhook/config/job.sh
helm-charts/stable/amazon-eks-pod-identity-webhook/config/mutatingwebhook.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/ClusterRole.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/ClusterRoleBinding.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Deployment.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/NOTES.txt
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Role.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/RoleBinding.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Service.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/ServiceAccount.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/_helpers.tpl
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/job-ClusterRole.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/job-ClusterRoleBinding.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/job-ConfigMap.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/job-CronJob.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/job-Job.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/job-ServiceAccount.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/values.yaml
release/config/crds/distro.eks.amazonaws.com_releasechannels.yaml
release/config/crds/distro.eks.amazonaws.com_releases.yaml
release/config/examples/release_example.yaml

This PR adds a helm chart to deploy the amazon-eks-pod-identity-webhook and automates applying the MutatingWebhookConfiguration and approving the certificate through a job in post-install/upgrade as well as a cronjob that runs to be able to look for pending requests when the certificate is about the expire. This tries to mimic the cluster-up target in the upstream Makefile: https://github.com/vivek-koppuru/amazon-eks-pod-identity-webhook/blob/master/Makefile
This PR will be followed by the CDK infra changes to add this helm chart and pass in the necessary values, such as the image of the webhook and the fargate value based on the stack.
The MutatingWebhookConfiguration is applied during the jobs to be able to retrieve the CA_Bundle from …

Add amazon-eks-pod-identity-webhook to Helm charts

---

helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Deployment.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Service.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/values.yaml

Adding parameters to webhook so that default token expiration is 3600 and sts regional endpoint is set to true.
Not modifying version as we haven't deployed this yet.

Add token-expiration and sts-regional-endpoint flags

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/config/job.sh
helm-charts/stable/amazon-eks-pod-identity-webhook/values.yaml

Rename pod identity webhook to avoid replacing configuration by eks. Also fixed quotes in job script to be able to use the env var in the string, and increased sleep and loop count.

Rename webhook so it doesn't override eks webhook

---

helm-charts/stable/amazon-eks-pod-identity-webhook/values.yaml

The Service name doesn't support starting with a number, so changing the name. However, if we still want to include the number for the mutatingwebhookconfiguration resource, we can append that to the name of that resource or split up the naming in values.
Took an initial look into why the linting isn't catching the fact that this PR isn't modifying the version in Chart.yaml, but couldn't find anything. Will look more into it later.

Update name of webhook

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/config/install.sh

The loop for the job that deploys in our fargate cluster is too long, causing a timeout when helm is waiting for the hook to finish. I didn't encounter this issue on my devstack, but the csr's got approved within the first 2 loops, so 10 should definitely be enough for us.

Decrease loop for install.sh in pod-identity-webhook helm chart

---

builder-base/Dockerfile
builder-base/bash-checksum
builder-base/install.sh

Running make test from the upstream kubernetes source requires bash version of 4.3 or higher.  Amazon linux ships with 4.2 and there doesn't seem to be a way to get it without building it from source.
I have built this docker image locally and built kubernetes and run the unit tests with it.
light reading:
https://github.com/kubernetes/kubernetes/issues/82605
https://github.com/kubernetes/kubernetes/issues/78702

Add bash 4.3 to builder base to support kubernetes make test

---

builder-base/Makefile
builder-base/README.md
eks-distro-base/Makefile
eks-distro-base/README.md

Adding PR creation info to README's, remove unnecessary steps from builder-base Makefile, fix varnames in eks-distro-base Makefile.

Qualify README, improve consistency of Makefiles

---

builder-base/Makefile
eks-distro-base/update_base_image.sh
pr-scripts/create_pr.sh

- Fixed `sed` command for main Makefile which was referencing an old variable
- Fixed `sed` command for PR body
- Fixed the push errors by configuring git

Fix sed command for Makefile, resolve git push errors

---

builder-base/update_base_image.sh
eks-distro-base/Makefile
pr-scripts/create_pr.sh

The `gh pr create` command expects quotes around the PR body and title strings. Changed the other files to trigger the jobs.

Quote PR body and title in PR creation command

---

eks-distro-base/update_base_image.sh
pr-scripts/create_pr.sh

Kubernetes/Kubernetes project does not use the EKS Distro base image and hence we should skip tag update in that Makefile.

Skip image tag update for Kubernetes project

---

eks-distro-base/Makefile
eks-distro-base/check_update.sh

Qualifying the conditional for the `update` target invoked by the EKS Distro base periodic job with an additional check. Adding missing semicolon.

Improve the conditional construct for periodic job target

---

helm-charts/stable/cloudwatch-agent/.helmignore
helm-charts/stable/cloudwatch-agent/Chart.yaml
helm-charts/stable/cloudwatch-agent/README.md
helm-charts/stable/cloudwatch-agent/templates/_helpers.tpl
helm-charts/stable/cloudwatch-agent/templates/cloudwatch-agent-configmap.yaml
helm-charts/stable/cloudwatch-agent/templates/cloudwatch-agent-daemonset.yaml
helm-charts/stable/cloudwatch-agent/templates/cloudwatch-agent-role-binding.yaml
helm-charts/stable/cloudwatch-agent/templates/cloudwatch-agent-role.yaml
helm-charts/stable/cloudwatch-agent/templates/cloudwatch-agent-service-account.yaml
helm-charts/stable/cloudwatch-agent/values.yaml

Modified the cloudwatch-agent part of this [file](https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluentd-quickstart.yaml) and turned into a helm chart. Also made changes in service account creation logic, daemonset permissions etc.

Add helm chart for cloudwatch

---

builder-base/golang-checksum
builder-base/install.sh

Changes enable installation of multiple versions of go in our builder base image so that we can choose what version of the go binary to run based on the project we are building. This takes advantage of installing specific versions of go using `go get` as explained in this link: https://golang.org/doc/manage-install. Also updated the default go binary on the image to 1.15 so we wouldn't have to worry about using an older default.
Then, for each of our projects or the kubernetes version that we are trying to build, we can add an export to our path to include the path to this binary before the default version that a customer may have. That way, since the scope of the path would only be during the duration of the script, the go build will …

Add multiple versions of go

---

builder-base/update_base_image.sh

Using the PULL_BASE_SHA environment variable for simulating the changes in the presubmit jobs could cause issued since it would essentially be trying to replace the existing tag with the same new tag value. This causes `git add` to not add any files, hence `git commit` fails with exit code 1 since there are no files to commit.
Hence for presubmits, we could use `PULL_PULL_SHA`, a job environment variable from the presubmit CI environment which refers to the SHA of the head commit of the PR against which the job runs.

Use PR branch ref SHA for presubmits instead of base ref

---

builder-base/install.sh

This is a continuation of https://github.com/aws/eks-distro-build-tooling/pull/86 and related to https://github.com/aws/eks-distro/pull/114
Since we don't need to know the minor version and only will use golang binaries based on the major version, such as "1.15", I am modifying the path that we are storing them in so for the related PR, we won't have to hardcode the versions in our script.
Also modified to just using a function instead so I can make use of local variables, and after some discussions on functions vs loops earlier.

Remove minor version from our paths for golang

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Deployment.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/values.yaml

Adding default region flag so that the webhook can append `AWS_REGION` and `AWS_DEFAULT_REGION` environment variables to the pod to be able to make use of the regional STS endpoints. This link mentions that the region needs to be set as well in order to make use of regional endpoints, and I noticed in our pods that the region wasn't being set: https://docs.aws.amazon.com/credref/latest/refdocs/setting-global-sts_regional_endpoints.html
The region field is configurable so that it can set in our infrastructure when deploying the helm chart. 

Add default aws region to pod-identity-webhook

---

builder-base/install.sh

Though AWS CLI version 2 is generally available, the builder-base image still uses version 1 of the CLI since it is downloaded via `yum` and the latest available version in the `yum` repositories is `1.18.147`. Hence we should install version 2 using [these instructions](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#cliv2-linux-install).

Install AWSCLIv2 on builder-base image

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/config-ConfigMap.yaml
helm-charts/stable/prow-control-plane/templates/plugins-ConfigMap.yaml

Add support for empty repositories list in CP values. 
Currently, if we pass in empty repositories to prow-control-plane helm chart, it will create invalid ConfigMaps. This PR solves that issue.

Add support for empty repositories list in CP values

---

release/pkg/assets_k8s.go

N/A
We were building/uploading kubeadm for linux, but neglected to include it in the release CRD. Future releases will now include it

Add linux kubeadm binary to release CRD

---

builder-base/install.sh

Build specific commit of amazon-ecr-credential-helper so that we don't hit the global sts endpoint. We need to do this as it has been a year since a release has happened for that repo, and we need to consume this specific commit: https://github.com/awslabs/amazon-ecr-credential-helper/pull/240

Build specific commit of amazon-ecr-credential-helper

---

release/cmd/release.go
release/pkg/assets_attacher.go
release/pkg/assets_authenticator.go
release/pkg/assets_cni.go
release/pkg/assets_coredns.go
release/pkg/assets_etcd.go
release/pkg/assets_k8s.go
release/pkg/assets_livenessprobe.go
release/pkg/assets_metricsserver.go
release/pkg/assets_provisioner.go
release/pkg/assets_registrar.go
release/pkg/assets_resizer.go
release/pkg/assets_snapshotter.go
release/pkg/generate_spec.go
release/pkg/kube_reader.go

Generate CRD from generated artifact directory. Previously, we were generating from all over the repo in the _output directories. This will help ensure that the artifact directory matches the CRD.

Generate release CRD from artifact directory

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/crier-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/deck-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/ghProxy-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/hook-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/horologium-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/prow-controller-manager-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/sinker-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/tide-Deployment.yaml
helm-charts/stable/prow-control-plane/values.yaml

Add prometheus annotations to Prow pods to scrape metrics

Add prometheus annotations to Prow pods to scrape metrics

---

release/Makefile
release/api/v1alpha1/release.go
release/api/v1alpha1/releasechannel.go
release/cmd/release.go
release/config/crds/distro.eks.amazonaws.com_releasechannels.yaml
release/config/crds/distro.eks.amazonaws.com_releases.yaml
release/pkg/assets_attacher.go
release/pkg/assets_authenticator.go
release/pkg/assets_cni.go
release/pkg/assets_coredns.go
release/pkg/assets_etcd.go
release/pkg/assets_k8s.go
release/pkg/assets_livenessprobe.go
release/pkg/assets_metricsserver.go
release/pkg/assets_provisioner.go
release/pkg/assets_registrar.go
release/pkg/assets_resizer.go
release/pkg/assets_snapshotter.go

These CRD changes are causing incompatibilities. We did this for tests, we are no longer using that approach. This is just a straight `git revert` on PR 103

Revert "Release number as string (#103)"

---

builder-base/Dockerfile
builder-base/install.sh
builder-base/rootlesskit-checksum

Adding rootlesskit from rootless-containers to builder-base image. This helps to run buildkitd in rootless mode.

Adding rootlesskit to builder base image

---

helm-charts/scripts/verify-version.sh

Change `PREV_RELEASE_HASH` to `PULL_BASE_SHA` in `verify_version.sh` to fix `helm-chart-tooling-presubmit` prowjob

Change PREV_RELEASE_HASH to PULL_BASE_SHA

---

helm-charts/scripts/install-toolchain.sh
projects/grafana/helm-charts/Makefile

Currently PROW clusters use managed Grafana. This prevents us from using the declarative approach of adding dashboards for Grafana. So we are switching to using the upstream helm chart to install grafana and configure the dashboards.

Import upstream grafana chart and publish to S3 for PROW

---

release/pkg/assets_authenticator.go
release/pkg/assets_coredns.go
release/pkg/assets_metricsserver.go

Adding support for CRD generation for resources coredns, aws-iam-authenticator and metrics server for release version dependent GIT_TAG.

Handling CRD generation support for release based GIT_TAG

---

builder-base/update_base_image.sh
eks-distro-base/check_update.sh
pr-scripts/create_pr.sh

The Dockerfile generated was being hardcoded with an exit code of 0 since the Heredoc did the variable expansion of `$?` instead of keeping it as such.

Prevent heredoc from expanding Bash exit code variable

---

builder-base/Dockerfile
builder-base/buildkit.sh

Adding script to builder-base image to perform image builds in CodeBuild in daemonless mode. This script was largely inspired from https://github.com/moby/buildkit/blob/master/examples/buildctl-daemonless/buildctl-daemonless.sh, and slightly modified to suit our usecase.

Add script to run buildctl in daemonless mode

---

builder-base/install.sh

With the builder-base jobs, we need to install the Github cli in the pod running the job (the image being ECR-vended AL2) in order to perform the actual update of builder-base PR's on prowjobs, in addition to baking it into the builder-base image itself to be used in other jobs performing PR updates (attribution files, eks-distro-base image).

Install GH cli locally in addition to builder-base

---

builder-base/install.sh

I added a call to dig in eks-distro to help debug some sporadic dns issues, but dig is missing.  bind-utils includes it.

adding bind-utils for the dig command on builder-base

---

builder-base/goss-checksum
builder-base/install.sh
builder-base/packer-checksum
builder-base/rootlesskit-checksum

Adding packer, ansible, goss and pywinrm to builder-base.
These dependencies are used by kubernetes-sigs/image-builder to create capi images.
We will be removing older version of packer and installing a more stable and newer version with this change.

Adding image-builder dependencies to builder-base

---

pr-scripts/create_pr.sh

We don't want the script to invoke `git commit` and fail if no files were modified, and thus no files were added.

Exit gracefully if no files were changed

---

builder-base/install.sh

Image-builder requires goss to be present under the imagebuilder user home path.
This change untars the goss plugin onto the right path.

Untaring goss onto imagebuilder home paths

---

builder-base/govc-checksum
builder-base/install.sh

Adding govc to base to run govc commands and interface with vsphere.

Adding govc to builder base

---

builder-base/golang-checksum
builder-base/install.sh

Updating the go versions and also the default go for our builder base. This should not break existing dependencies because the ones that are tied to specific versions have overrides, and we should always be updating our default go version in the builder base. This is also needed to consume the embed package for the CLI.

Update golang versions

---

builder-base/Makefile
eks-distro-base/Makefile

Add a Make target for `all`. Also triggers base image jobs to ultimately push to public ECR 🤞.

Add Makefile target for complete builds of base images

---

pr-scripts/create_pr.sh

We are tracking builder-base image in a separate file. The automated PR should update the tag in that file too when a new image is created.

Modify script to automate builder-base image tag update in tag file

---

generate-attribution/generate-attribution-file.js

This came up when adding attribution generation for capd since it pulls in capi deps from higher up in the repo path (../../)

attribution: better handling of relative path replace paths

---

builder-base/Makefile
eks-distro-base/Makefile
scripts/setup_public_ecr_push.sh

This setup script makes sure we use the proper Role to push to the `eks-distro-build-tooling` repo where we have the base image repos.
/hold

Set up base image pushes to eks-distro-build-tooling ECR public registry

---

builder-base/Makefile
eks-distro-base/Makefile
scripts/setup_public_ecr_push.sh

Fixing the region in the script; sleep increase is just to trigger image builds.

Increase sleep before building images, fix region as us-east-1 for ECR public push

---

builder-base/goss-checksum
builder-base/install.sh
builder-base/packer-checksum
builder-base/yq-checksum

Updated image-builder tag which needs newer packer+ansible. Also adding yq for parsing the eks-d release yaml

builder-base: update package/ansible and add yq

---

builder-base/Makefile
eks-distro-base/Makefile

This script has now been moved to the Prowjobs to be invoked before the make target.

Remove ECR setup scripts from Makefile

---

builder-base/Makefile
eks-distro-base/Makefile
eks-distro-base/check_update.sh
projects/aws/amazon-eks-pod-identity-webhook/Makefile
projects/infinityworks/github-exporter/Makefile
projects/prometheus/alertmanager/Makefile

We don't need this variable anymore, since we are consuming public ECR images by default.

Remove DEVELOPMENT var from build-tooling projet Makefiles

---

builder-base/install.sh

For generating config files on the fly based one eks-distro release yaml, Id like to use envsubst which is provided by gettext.

install gettext on builder base for envsubst

---

builder-base/install.sh

Install docker on builder-base to build kind node image

Add docker to builder-base

---

builder-base/Dockerfile
builder-base/docker.sh

We can use this script to kick off the docker daemon for building kind images

Add docker daemonless script to builder-base image

---

builder-base/buildkit-checksum
builder-base/install.sh

For kind image builds, the dockerfile uses `copy --chmod` which is a newer buildkit feature.  Upgrading to get support for that

builder-base: bump to latest version of buildkit

---

release/pkg/assets_etcd.go

*Problem:*
* Prow job [fails](https://prow.eks.amazonaws.com/view/s3/prowdataclusterstack-316434458-prowbucket7c73355c-1n9f9v93wpjcm/logs/dev-release-1-20-postsubmit/1393357204056182784#2:build-container-build-log.txt%3A15064)
* Fixes bug from https://github.com/aws/eks-distro-prow-jobs/pull/177
* Related to other bug fix https://github.com/aws/eks-distro/pull/357

Fixed bug related to etcd GIT_TAG

---

eks-distro-base/Makefile

We need the buildkit check for postsubmits and periodics since we call `buildctl` here as well.

Add buildkit check for postsubmit and periodic make targets

---

eks-distro-base/Makefile

The env vars set by the script are not available in the same shell as the one in which the make target is invoked.

Configure ECR Public push setup script and make target to run in same shell

---

eks-distro-base/Makefile

Makefile by default uses `sh` shell, which doesn't implement source. Hence we are changing it to use `bash` shell so that the periodic can source the setup script.

Use Bash shell in Makefile to source script

---

eks-distro-base/Makefile

Fixing the Makefile to run the check-update script only once during the periodic.
/hold

Avoid re-running check-update script in periodic

---

builder-base/hugo-checksum
builder-base/install.sh

This adds hugo binary to the base container build.

Add hugo binary to base docker container

---

generate-attribution/generate-attribution-file.js

Waiting for an async method inside a Promise closure is kind of an anti-pattern.

Call async function outside return statement

---

.gitignore
eks-distro-base/Makefile

The create-pr target is called by default in the Prowjobs, and while we want to call the PR script for presubmits (dry-run) and postsubmit (always create PR due to deterministic image push), we need a condition to check if images were pushed in periodic, to decide if a PR is to be created.

Create pull-requests conditionally in periodic

---

eks-distro-base/Dockerfile.minimal
eks-distro-base/Dockerfile.minimal-nonroot
eks-distro-base/files/etc/group
eks-distro-base/files/etc/nsswitch.conf
eks-distro-base/files/etc/os-release
eks-distro-base/files/etc/passwd

- Instead of using nsswitch from al2, use a more generic similar to distroless
- add passwd/group files to define root and nonroot users
- add os-release file similar to distroless 

minimal image: add nonroot variant and clean up static files

---

projects/grafana/helm-charts/Makefile

Upgrading the Grafana helm chart to version 6.14.1 created some unexpected network errors in my Grafana dashboard, so downgrading to see if the new version fixes the issue. 

Downgrading Grafana helm chart version to 6.13.6

---

builder-base/buildkit-checksum
builder-base/golang-checksum
builder-base/install.sh

* Bumped buildkit version to latest release, that involves bug fixes
* Bumped up patch versions for Golang

Bump up buildkit version and Golang patch versions

---

eks-distro-base/Dockerfile.minimal
eks-distro-base/Makefile

Avoid building images just to export, only run export on images that built/pushed.

only export if the image has been pushed

---

release/pkg/assets_attacher.go
release/pkg/assets_authenticator.go
release/pkg/assets_cni.go
release/pkg/assets_coredns.go
release/pkg/assets_livenessprobe.go
release/pkg/assets_metricsserver.go
release/pkg/assets_provisioner.go
release/pkg/assets_registrar.go
release/pkg/assets_resizer.go
release/pkg/assets_snapshotter.go

Fix comments for release asset component methods.

Fix comments for asset component methods

---

builder-base/buildkit.sh
builder-base/docker.sh
builder-base/install.sh
builder-base/update_base_image.sh
eks-distro-base/Makefile
pr-scripts/create_pr.sh

This change actually creates PRs for `eks-anywhere-build-tooling` repo.

Create base image PRs for eks-anywhere-build-tooling

---

pr-scripts/create_pr.sh

The same conditions and assignments apply to the eks-anywhere-build-tooling repo too.

Add EKS-A build tooling repo to condition

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/plugins-ConfigMap.yaml
helm-charts/stable/prow-control-plane/values.yaml

Modify config updater plugin to map registry entrypoint script to ConfigMap on presubmits cluster.

Add registry endpoint script to config updater

---

builder-base/Dockerfile
builder-base/Makefile
builder-base/install.sh

Fixing the issue with removal of `gofmt` binary.
More cleanup to decrease image size.

Cleanup Go source code, bring back gofmt

---

release/pkg/clients.go
release/pkg/generate_spec.go

Prevents the print statements from getting piped into output file.

Remove print statements from output except for error

---

builder-base/install.sh

Install openssl devel package for Tuftool build.

Install openssl devel for OpenSSL lib headers

---

helm-charts/scripts/install-toolchain.sh
helm-charts/scripts/verify-version.sh
helm-charts/stable/binfmt/.helmignore
helm-charts/stable/binfmt/Chart.yaml
helm-charts/stable/binfmt/README.md
helm-charts/stable/binfmt/templates/binfmt-DaemonSet.yaml
helm-charts/stable/binfmt/values.yaml

Adding helm charts for deploying the `binfmt` container on clusters to enable QEMU emulation.

Add Helm charts for deploying binfmt Daemonset

---

generate-attribution/generate-attribution-file.js

When a module is not found by a string match, a second search is done looking for matches based on prefix.  For ex, 
`k8s.io/apimachinery/third_party/forked/golang` is in the licenses.csv file but does not support up directly in the go-deps.json file.  Instead it gets matched against `k8s.io/apimachinery/third_party/forked/golang/reflect`, which is fine.  What was happening before is it would also match against `k8s.io/api`.  This adds a check to only match the one that has the longest prefix.

attribution: improve prefix matching of modules

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Deployment.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/install-CronJob.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/install-Job.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/uninstall-Job.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/values.yaml

This is to help us constrain what nodes these pods get deployed on.
**Note:** I chose to use `nodeAffinity` instead of `nodeSelector` since the former is a superclass of and provides a more expressive way to schedule nodes than the latter, and at some point, `nodeSelector` will be deprecated (although not until K8s launches v2 API).

Add affinity spec to Helm chart values and templates

---

eks-distro-base/Makefile
eks-distro-base/update_base_image.sh

The EKS Anywhere cluster controller image uses the minimal eks-d base as the base image, so that tag file needs to be update accordingly when a new image is pushed.

Add eks-anywhere repo to base image tag update workflow

---

pr-scripts/create_pr.sh

This is to set the proper title and body in the PR created to bump image tag in eks-anywhere repo.

Fix PR creation parameters for eks-anywhere repo

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/plugins-ConfigMap.yaml

The `override` plugins allows PR authors to force job statuses on Github to pass. This is especially useful when adding new blocking presubmits (for example, adding presubmit for a new project) which causes the status reconciler to run the job on all open PRs and fail citing the path references by the job doesn't exist ([example](https://github.com/aws/eks-anywhere-build-tooling/pull/228)).
The `needs-rebase` plugin is an external plugin whose events are not handled by Prow's hook component but through an external endpoint that has been configured to handle GitHub webhooks. We don't have support for it at this point, so removing it.

Add override plugin, remove needs-rebase plugin

---

builder-base/install.sh

YQ download was refactored to download the binary directly from the releases instead of from the tarball and unpacking it. Turns out the binary inside the tarball has exec perms on it,  but the standalone binary from release does not.

Add exec permissions to yq binary

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/crier-Deployment.yaml

Crier pods need the kubeconfig mounted on them to facilitate communication with the presubmit and postsubmit clusters to get the pod info.

Mount kubeconfig on crier pods for dataplane cluster communication

---

Makefile
eks-distro-base/Dockerfile.minimal-base-docker-client
eks-distro-base/Dockerfile.minimal-base-git
eks-distro-base/Dockerfile.minimal-base-haproxy
eks-distro-base/Dockerfile.minimal-base-iptables
eks-distro-base/Dockerfile.minimal-base-kind
eks-distro-base/Dockerfile.minimal-base-nginx
eks-distro-base/Makefile
eks-distro-base/scripts/enable_docker_install
eks-distro-base/scripts/install_if_al2
eks-distro-base/scripts/install_if_al2022
eks-distro-base/scripts/remove_package

This adds an experimental build of our base images based on al2022 instead al2.  Al2022 is not officially released yet, but the plan is to build new base images along with the existing al2 images and tag differently.  We can then use these to test in eks-d and eks-a repos.  There is no current rollout plan other than just verification. 
*NOTE:* AL2022 does not include docker/containerd/runc, yet.  We are doing a really hacky thing here by pulling these from the al2 repo and will do some validation via the kind image, which runs kube inside of a docker container, to confirm if it actually works.
Prow: https://github.com/aws/eks-distro-prow-jobs/pull/259
/hold
By submitting this pull request, I confirm that you can use, modify, copy, and …

distro-base: add al2022 build option to use new al2022 as the base image

---

release/cmd/release.go

Currently the dev release manifests are pointing to the prod cdn, which is causing our builds from the EKS-A side to fail because the artifacts don't exist in the urls specified. This will read the bucket from the env var and if the dev-release flag is set, use the dev url instead.

Modify url for dev releases

---

builder-base/install.sh

We use [linuxkit](https://github.com/linuxkit/linuxkit) for building [tinkerbell/hook](https://github.com/tinkerbell/hook) OSIE.
Hence adding it builder-base image. 

Adding linuxkit binary to builder-base image

---

builder-base/Makefile
builder-base/amazon-ecr-cred-helper-amd64-checksum
builder-base/install.sh
builder-base/update_base_image.sh
builder-base/update_shasums.sh
builder-base/versions.sh

This introduces an al2022 based builder-base image.  It also changes the base image from al2/2022 directly to the minimal kind image, which has most of the same stuff this image needs.  
Much like the eks-distro-base build, this adds an AL_TAG which is meant to be used to determine the underlying base image.  The al2 build continues to be tagged latest, as well as latest.2, and the 2022 build will be tagged with latest.2022.

builder-base: add al2022 build

---

builder-base/update_base_image.sh
builder-base/update_shasums.sh
pr-scripts/update_image_tag.sh

- Forgot to update the shasum script to get aws ecr helper arm checksum
- Fix update of BUILDER_BASE_TAG_FILE files in eks-distro-prow-jobs

builder-base: fix prow-jobs update and shasum update

---

builder-base/install.sh

We ran into an issue yesterday in codebuild where a job tried to switched to the root user and was not able to because the shell was improperly configured.

builder-base: set root user shell to bash instead of nologin

---

release/pkg/assets_k8s.go

In https://github.com/aws/eks-distro/pull/753 I am looking to change the KUBE_GET_VERSION in the version file the release tooling uses to generate the final release yaml.  Image tags and binary versions will not match on the kubernetes components.  This change uses the same process to generate the image tags as all the other components in the release tooling. 
At this point the only thing the release tooling will be pulling from the version file is the git commit hash.
/hold

release: kube generate image tags like all other container images

---

eks-distro-base/Makefile
pr-scripts/create_pr.sh

The last periodic job that update the distro base images did not check in the updates file which tracks the packages that were changed.  This meant that when the other PRs were opened, the message showed the previous updated packages instead of the latest.  This should fix that.
I took a simple approach here... the ADDITIONAL_GIT_ADD was only used in this one spot and the quotes around multiple were messing up the git add.  Instead of improving that for one case and since this script is already hardcoding cases for different repos, I took this approach.

distro-base: check in updates file for use in pr creation

---

pr-scripts/create_pr.sh
projects/kubernetes/test-infra/Makefile
projects/kubernetes/test-infra/docker/linux/Dockerfile
projects/kubernetes/test-infra/docker/linux/deck/Dockerfile
projects/kubernetes/test-infra/update_helm_chart.sh
projects/kubernetes/test-infra/update_helm_images.sh

We were already pushing the deck image into ecr since we were "patching" it.   This brings over some of the common.mk patterns to "build" the other images, these builds are just a simple mirror at this point.
The update script is updated to update all the prow image names.
TODO:
/hold

prow: mirror other images into ecr by introducing build

---

release/pkg/assets_attacher.go
release/pkg/assets_livenessprobe.go
release/pkg/assets_provisioner.go
release/pkg/assets_registrar.go
release/pkg/assets_resizer.go

Dev release 1.22 failed due to the changes to the csi projects being release branch'd.  I ran these changes locally to generate the CRD to ensure they fix the issue. I will retrigger the build once this merges.

release: fix git tag generation for projects which were split

---

EKS_DISTRO_TAG_FILE.yaml

The build timed out building all the images.  This updates the ones that did build and changes the tag for the ones that didnt to force them to build during the next periodic.

update to recently build al2022 image tags

---

release/config/crds/releasechannels.distro.eks.amazonaws.com-v1alpha1.yaml
release/config/crds/releases.distro.eks.amazonaws.com-v1alpha1.yaml

1.22 deprecates v1beta1 apiextensions: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22
Made changes by applying the crd on a 1.21 cluster and retrieving the v1 version of it so it would automatically convert it for me.

Change apiextensions to use v1 api

---

eks-distro-base/update_base_image.sh
pr-scripts/update_image_tag.sh

In the last periodic build a couple things happened.
- the update_packages were not being checked in so the PR messages in other repos were still wrong
- the update base image tag script was also updating al2022 when it should have only been updating the al2 ones. This is because the image tags are the same between the two.

distro-base: fix update_packges and update image tag

---

EKS_DISTRO_TAG_FILE.yaml
eks-distro-base/Makefile

In the latest run the export targets ended up triggering full builds even though they should have used cached layers.  I believe now that we have the garbage collecting turned on, these cached layers are getting cleaned up during building other images.  This moves exporting to happen right after building to try and avoid this.
Also updated to the built tags for al2022.

distro-base: update al2022 tags and fix export

---

helm-charts/patches/prow-control-plane/0001-EKS-D-changes-to-helm-control-plane-chart.patch
helm-charts/scripts/verify-version.sh
helm-charts/stable/prow-control-plane/Chart.yaml

This was removing a preceding `-` that caused validations since it thought it was a map and not an array.

Fix Deck service ports mapping

---

builder-base/install.sh

builder-base: fix 1.18 install due to missing patch version

---

eks-distro-base/Makefile
pr-scripts/open_pr_check.sh

To avoid building new images day after day if an update PR is missed and left open, bail out if the PR already exists.  This happened the last time we had a periodic update and the images were built twice, 2 days in a row, because we did not merge the PR in time.

distro-base: bail out early if a update PR already exists

---

.gitignore
helm-charts/patches/prow-control-plane/0001-EKS-D-changes-to-helm-control-plane-chart.patch
helm-charts/stable/prow-control-plane/Chart.yaml

Upon testing the latest version of our Prow Controlplane helm chart (`v1.0.25`), I noticed that all of the pods having the deck-url arg were in `CrashLoopBackOff` with similar error messages
```
$ k logs hook-54d7849898-8xtv9
flag provided but not defined: -deck-url
Usage of /ko-app/hook:
-bugzilla-api-key-path string
Path to the file containing the Bugzilla API key.
-bugzilla-auth-method string
Which authorization method will be used. Values can be bearer, query or x-bugzilla-api-key.
-bugzilla-endpoint string
Bugzilla's API endpoint.
...
```
```
$ k logs horologium-6987f9b545-pkkbk
flag provided but not defined: -deck-url
Usage of /ko-app/horologium:
-config-path string
Path to the prowconfig
-dry-run
Whether or not to make mutating API calls to Kubernetes. (default true)
-health-port …
```

Remove unsupported Deck URL flag from patch

---

helm-charts/patches/prow-control-plane/0001-EKS-D-changes-to-helm-control-plane-chart.patch
helm-charts/stable/prow-control-plane/Chart.yaml

The Controlplane sinker role needs these permissions to delete pods on the dataplane clusters.

Add pod-level permissions to Prow Sinker role

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/config-ConfigMap.yaml

This will make it easier to spot the errors in Prow build logs in Spyglass.
This list includes error messages across different scenarios such as Go compilation, unit tests, bash scripts, shasum checks, git workflows and other generic formats.

Add list of build log regexes for highlighting

---

helm-charts/Makefile
helm-charts/Prow.mk
helm-charts/patches/prow-control-plane/0001-EKS-D-changes-to-helm-control-plane-chart.patch
helm-charts/stable/prow-control-plane/Chart.yaml

Not setting this caused Sinker to run in dry-run mode where it did not delete any pods although logs claimed it was.

Set dry-run flag to false for Sinker

---

builder-base/install.sh

Projects are now depending on 1.17 syntax which 1.16 can not parse.  I ran into this updating the kustomize-controller. The exact error is:
`github.com/hashicorp/vault/sdk/version: vendor/github.com/hashicorp/vault/sdk/helper/pluginutil/run_config.go:13:2: //go:build comment without // +build comment`
We have been always using go 1.16 when running go list and gather-licenses because of the way go-licenses finds the dependencies it needs to be installed via the version of go that is currently highest in the path when running.  Now that we have projects using 1.17 we need to support using go-licenses installed with both 1.16 and 1.17.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

builder-base: install go-licenses with 1.17 too

---

eks-distro-base/Dockerfile.minimal-base-haproxy
eks-distro-base/scripts/eks-d-common
eks-distro-base/scripts/validate_libraries

validate_libraries is meant to ensure for every exec in the image, the necessary dynamic libs are present.  This uses ldd to figure this out.  The current version has a bug where this was only checking the first lib returned from ldd, this pr fixes this to the expected behavior.

distro-base: fix validate_libraries

---

Makefile
eks-distro-base/Dockerfile.minimal-base-git
eks-distro-base/Dockerfile.minimal-helpers
eks-distro-base/scripts/clean_docs
eks-distro-base/scripts/clean_install
eks-distro-base/scripts/cleanup
eks-distro-base/scripts/eks-d-common
eks-distro-base/scripts/install_binary
eks-distro-base/scripts/install_deps_for_binary

This PR sets up for future minimal images which are more tailored for the exact use case.  For ex, the ebs csi driver team has asked us to help them with a minimal image for them.  The ebs csi driver has a set of known exec's that it will exec out to and ideally we could build an image with those execs and their required libraries.  We could also look at using this approach for some of our existing images, like nginx + haproxy + docker-client, to clean up those dockerfiles. 
*Note* This PR only includes to the scripts to keep the PR as small as possible and properly document this new approach.  I have tested a ebs csi driver image with the ebs team using these scripts to validate it passes their e2e suite.
To review the existing design: …

distro-base: Adds new install_binary scripts

---

eks-distro-base/Makefile
eks-distro-base/tests/Dockerfile
eks-distro-base/tests/check_git.go
eks-distro-base/tests/run_tests.sh
pr-scripts/eks_distro_base_pr_body

The tests will now automatically run if docker is available after a build of one of the minimal images.  There is also a new target to make it easier to run the tests against the already built/published images to validate after automated updates.

distro-base: makes it easier to run minimal image smoke tests

---

pr-scripts/create_pr.sh
pr-scripts/eks_distro_base_other_repo_pr_body

I updated the message recently, but didnt think about how it was used for both PRs to this repo and to other repos. For ex: 
https://github.com/aws/eks-anywhere-build-tooling/pull/942 is not ideal
This adds a different body file for the other repos.

distro-base: Use seperate message for other repos

---

builder-base/install.sh

Bump patch versions for Go 1.17 and 1.18 to the latest available at https://go.dev/dl/
/hold

Bump patch versions for Go 1.17 and 1.18

---

builder-base/Dockerfile
builder-base/install.sh
builder-base/versions.sh

Installing tuftool in builder base so it's readily available during builds.

Add tuftool to builder-base

---

builder-base/install.sh

builder-base: use 1.15 from upstream since al2 isnt the latest

---

eks-distro-base/Makefile
eks-distro-base/check_update.sh

AL22 uses `releasever` which is different than al2.  Currently during their beta period, whenever they release a new build of al22 they are bumping the releasever and all new packages are under this version.  I think the best thing to do here is when there is a new releasever from al22 we should rebuild our images.  I want to watch what happens when they go ga and how often they are bumping new releasevers.
If they are going to be bumping the releasever more often than wed like to rebuild our minimal base images, the approach we can take is to get the latest releasever and pass that to `yum check --security --releasever=<>`. Well wait to see what happens post ga to do this.
By submitting this pull request, I confirm that you can use, …

distro-base: support updating al22 images if new releasever

---

eks-distro-base/Makefile
eks-distro-base/tests/run_tests.sh

I have been trying to run the tests manually after new images are built by prow. This changes the test code to use buildctl instead of docker so we can build for all platforms and run tests for all.  For the most part this works out well.
There is one gotcha with the nft tests. For some reason when running the image for a different arch than the host, it will fail to load. The current arch will load just fine. I have run these tests on both an amd and an arm instance to confirm both images pass the test.

distro-base: Runs tests for all platforms built/pulled

---

eks-distro-base/Dockerfile.minimal-base
eks-distro-base/Dockerfile.minimal-base-csi
eks-distro-base/Dockerfile.minimal-base-git
eks-distro-base/check_update.sh
eks-distro-base/scripts/eks-d-common
eks-distro-base/update_base_image_other_repos.sh

- AL22 images were not actually being built from the latest. The way al22 works with this releasever stuff is that yum upgrade doesnt actually get to the latest, if we do not set the new releasever.  This meant unless the AL22 team published new container images, which they do not always do, for each releasever would constantly rebuild our images because check update was correct but build was not.
- I found the above due to a build failure in the al22 postsubmit for the git variant.  This was due to the fact that a newer package from al22 had been released and what I tested with was on an image with an older releasever and therefore an older package.  A new bin had been added which we do not need so its been added to the unnecessary files …

distro-base: Various improvements to al22

---

eks-distro-base/Dockerfile.base
eks-distro-base/Dockerfile.minimal-base
eks-distro-base/Dockerfile.minimal-helpers
eks-distro-base/Makefile
eks-distro-base/check_update.sh
pr-scripts/create_pr.sh

When working locally i have wanted the ability to build an image along with the base image(s) it depends on. What i usually do is make minimal-images-base minimal-images-base-glibc minimal-images-base-iptables, which is annoying. I also think we could use this for presubmits to break them up a bit for this job, esp as we add more images.
Getting the order right for the various targets has always been an issue with all the wildcard rules and ive never really understood why. When introducing the dep building support, it was easier to go ahead and define most targets as actual targets, using variables since they are generated, to make the targets more clearly defined.
By submitting this pull request, I confirm that you can use, modify, copy, …

distro-base: add ability to be build dependent images

---

release/Makefile

Fix for error `/bin/sh: /home/prow/go/bin/controller-gen: No such file or directory` ([example](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro-build-tooling/445/eks-distro-release-tooling-presubmit/1554648215024832512#2:build-log.txt%3A51)) on eks-distro-release-tooling-presubmit jobs. This was caused by a recent [change](https://github.com/aws/eks-distro-build-tooling/commit/576b89eaf1edd40780fcbbf671ff6e66ca4163d8#diff-39c1d094a91b87c4c07eb89e6199ee313c46cebf77b8973080521046c3e0bfb6) to update Go from v1.16.15 to v1.18.4 in `builder-base/versions.sh`. According to the [Golang docs](https://go.dev/doc/go-get-install-deprecation), 
> Starting in Go 1.17, installing executables with go get is deprecated. go …

Changed make controller-gen to use go install

---

release/pkg/assets_cni.go

* Fix for failed `cat: ../../projects/containernetworking/plugins/GIT_TAG: No such file or directory ` in post submit build (see [example](https://prow.eks.amazonaws.com/view/s3/prowdataclusterstack-316434458-prowbucket7c73355c-1n9f9v93wpjcm/logs/build-1-20-postsubmit/1554617167037599744#2:build-container-build-log.txt%3A878)) due to this change creating release branches https://github.com/aws/eks-distro/pull/1157

Added channel to cni

---

projects/kubernetes/kops/Makefile
projects/kubernetes/kops/kops_artifacts_management_tools.sh
projects/kubernetes/kops/patches/0001-remove-hardcoded-requierment-on-flannel-plugin.patch

first steps for a project build to patch and build `nodeup` and fetch all of the other kOps binaries + images. if you run `make build` it will:
- clone kOps
- checkout out target version
- apply the patch to remove the flannel dependency to nodeup
- crossbuild nodeup
- pull all the kOps artifacts (binaries + imagse + checksums) for our target platforms + arches from artifacts.k8s.io 
-  generate a checksum for nodeup and copy it into the output dir
the next step here is going to be uploading these artifacts to an S3 bucket so we can source them from kOps, will be in another PR, just wanted to get some eyes on this.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

first pass at kOps patch + build

---

helm-charts/patches/prow-control-plane/0001-EKS-D-changes-to-helm-control-plane-chart.patch
helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/templates/config-ConfigMap.yaml
helm-charts/stable/prow-control-plane/templates/plugins-ConfigMap.yaml

This PR adds the required configuration and role permission rules to enable aborting Prowjobs via the Deck UI and is a follow-up to #469.
Also, trimming whitespace that was causing issues with pretty-printing  of `kubectl get` and `kubectl edit` output of the ConfigMaps.

Configure Deck to allow aborting Prowjobs

---

projects/golang/go/Makefile
scripts/sync_to_s3.sh

https://github.com/aws/eks-distro-internal/issues/206
golang release target, which is invoked by the post-submit.
this will run the whole rpm build process, and then run the s3-sync, syncing the output RPMs to the post-submit artifacts bucket for later consumption.

Golang release target

---

projects/golang/go/1.15/READEME.md
projects/golang/go/Makefile
scripts/sync_to_s3.sh

Update the make target to correctly upload the necessary artifacts to the post-submit bucket when we run 'release'.
Add simple README for go 1.15. 
This PR is primarily intended to trigger and test the presubmits and post-submits, and the readme will be expanded over time.

use correct sync path for Golang make release target; add readme

---

projects/golang/go/1.15/patches/0104-time-fallback-to-slower-TestTicker-test-after-one-fa.patch
projects/golang/go/1.15/rpmbuild/SPECS/golang.spec

https://github.com/aws/eks-distro-internal/issues/206
we saw the go 1.15 TestTicker tests failing on the post-submits cluster; this can happen on systems with limited CPU or which are over-loaded. Taking this upstream patch to solve this situation.
failure mode in prow post-submits cluster:
```
--- FAIL: TestTicker (2.47s)
tick_test.go:79: saw 5 errors
tick_test.go:37: 10 20ms ticks took 474.499355ms, expected [240ms,360ms]
tick_test.go:37: 10 20ms ticks took 499.98884ms, expected [240ms,360ms]
tick_test.go:37: 10 20ms ticks took 499.950458ms, expected [240ms,360ms]
tick_test.go:37: 10 20ms ticks took 520.10247ms, expected [240ms,360ms]
tick_test.go:37: 10 20ms ticks took 479.824555ms, expected [240ms,360ms]
FAIL
```
upstream CL fix: …

go 1.15 patch to support TestTicker test on overloaded systems

---

builder-base/install.sh

Add Go v1.19 to builder base

---

pr-scripts/builder_base_pr_body
pr-scripts/create_pr.sh
pr-scripts/prow_deck_pr_body

This PR adds a Prowjob logs link to the description of PRs that are opened by the eks-distro-pr-bot. This improves traceability of the PR automation.

Append job logs link to bot-authored PR descriptions

---

projects/golang/go/1.15/patches/0022-go-1.15.15-eks-archive-tar-limit-size-of-head.patch

There was an issue with applying the patch with git on a local branch after the --no-binary flag was used. Instead I updated the header to describe the removal of the file from the patch (since during the build the binary would still be an issue if included) and it's location in the repo.

1.15 binary patch fix

---

projects/golang/go/1.16/patches/0017-go-1.16.15-eks-regexp-limit-size-of-parsed-regexps.patch
projects/golang/go/1.16/rpmbuild/SPECS/golang.spec

#503 
Backported CVE-2022-41715 fix from go1.18

add patch for CVE-2022-41715

---

projects/golang/go/README.md

Add a basic README which includes installation instructions for the EKS Go version
*Testing*
Tested the instructions on an AMD64 AL2 EC2 instance w/out golang installed; it did what it was intended to do, installing the correct Go version from our RPM sources

add EKS Golang README with basic information and install instructions

---

projects/golang/go/1.16/README.md
projects/golang/go/Makefile

add a param to the go make file to specify the arch of the build

add arch selector for rpm build upload paths

---

EKS_DISTRO_TAG_FILE.yaml
eks-distro-base/Dockerfile.minimal-base

In the latest release of al22, from yesterday, they changed where the yum.repos config comes from. This adds the install for the new package.

Fixes missing yum repo config in al22

---

scripts/local_registry_check.sh

We ran into an issue yesterday where we were getting rate limited by docker hub pulling the registry container. @abhay-krishna fixed this to pull from ecr, but I figured it doesnst hurt to have a check like this which mirrors what we already do for buildkitd.

Adds local regi check to be used in presubmit

---

eks-distro-base/scripts/eks-d-common

In yesterdays periodic, the iptables arm image could not be built. From the logs it appears that the ldd was working fine for ebtables until all of a sudden it started segfaulting. Once it segfaulted, the code properly fell back to obdump, however objdump does not return full paths.  The libs for the binary in question, ebtables, are under /lib64/ebtables/* which the current code does not search for. 
This PR adds a fallback to find to search across the newroot folder for cases like this.

Falls back to find for looking for libs

---

EKS_DISTRO_TAG_FILE.yaml
eks-distro-base/Dockerfile.minimal-base-nginx

In the newest build of nginx in al2, they introduced the nginx-core package, similar to al22 which includes the mimetypes and other default config files.

Installs nginx-core along with nginx

---

projects/golang/go/1.15/README.md
projects/golang/go/1.16/README.md
projects/golang/go/1.17/README.md
projects/golang/go/1.18/README.md

update build badges on go version readmes to relfect arch builds

update build badges to relfect arch on readmes

---

projects/golang/go/1.16/rpmbuild/SPECS/golang.spec
projects/golang/go/1.17/rpmbuild/SPECS/golang.spec
projects/golang/go/1.18/rpmbuild/SPECS/golang.spec

https://github.com/aws/eks-distro-internal/issues/241
Set a uniform RPM release string for all EKS Go versions. In practice, this will look like `1.amzn2.eks`

update EKS Go RPM spec to include unified release string format

---

helm-charts/stable/prow-data-plane/Chart.yaml
helm-charts/stable/prow-data-plane/templates/buildkit-orchestration-Namespace.yaml
helm-charts/stable/prow-data-plane/templates/buildkit-orchestration-Role.yaml
helm-charts/stable/prow-data-plane/templates/buildkit-orchestration-RoleBinding.yaml

Add new templates for buildkit-testing role, rolebinding and namespace to the dataplane cluster Helm charts.

Add templates for buildkit-testing role, rolebinding and namespace

---

builder-base/install.sh
projects/golang/go/Makefile

https://github.com/aws/eks-distro-internal/issues/211
https://github.com/aws/eks-distro-internal/issues/241
Update the builder-base to use the 'prod' released versions of EKS Go.
Also allow over-riding the source and version of the EKS Go versions installed. This will be used for testing Go versions.
Unify the output path for both Dev and Prod releaes of EKS Go

use prod releases of EKS Go for builder-base

---

projects/golang/go/1.16/patches/0020-go-1.16.15-eks-syscall-os-exec-reject-environ.patch
projects/golang/go/1.16/rpmbuild/SPECS/golang.spec

Backport upstream Golang patch from source https://github.com/golang/go/commit/aba57b07721cac39b4b7cf70f8dfbf9e2e299187 to EKS Go 1.16 to fix CVE-2022-41716.
Update RPM Spec to incorporate patch into EKS Go 1.16

Eks go 1.16 CVE 2022 41716

---

projects/golang/go/1.17/patches/0004-go-1.17.13-eks-syscall-os-exec-reject-environ.patch
projects/golang/go/1.17/rpmbuild/SPECS/golang.spec

Backport a fix from source https://github.com/golang/go/commit/aba57b07721cac39b4b7cf70f8dfbf9e2e299187 to EKS Go 1.17 to patch CVE-2022-41716

backport patch for CVE-2022-41716 to EKS Go 1.17

---

projects/golang/go/1.16/patches/0021-go-1.16.15-eks-crypto-rand-properly-handle-la.patch
projects/golang/go/1.16/rpmbuild/SPECS/golang.spec

https://github.com/aws/eks-distro-build-tooling/issues/571 
Backport fix for CVE-2022-30634 to EKS Go 1.16.

backport patch for CVE-2022-30634 to EKS Go 1.16

---

projects/golang/go/README.md

https://github.com/aws/eks-distro-internal/issues/219
Update README to reflect our use of the EKS-D CDN for artifact distribution.
Include all currently supported EKS Go versions.
Fixes for clarity.

update readme to relfect prod release distribution via EKS D CDN

---

projects/golang/go/1.16/patches/0022-go-1.16.15-eks-os-exec-return-clear-error-for.patch
projects/golang/go/1.16/rpmbuild/SPECS/golang.spec

https://github.com/aws/eks-distro-internal/issues/255
Backport fix for CVE-2022-30580 to EK Go 1.16 from upstream 1.17

patch CVE-2022-30580 in EKS Go 1.16

---

projects/golang/go/1.16/patches/0023-go-1.16.15-eks-path-filepath-do-not-remove-pr.patch
projects/golang/go/1.16/rpmbuild/SPECS/golang.spec

https://github.com/aws/eks-distro-internal/issues/257
Backport fix for CVE-2022-29804 to EKS Go 1.16

patch CVE-2022-29804 in EKS Go 1.16

---

eks-distro-base/check_update.sh

We added the golang packages to the rpm db for the new golang compiler images. This was mainly to keep our db as accurate as possible and to make it easier to use these images to build future golang rpms.  Because our rpms are named the same as the yum provide golang packages, yum sees them as needing security updates.  We do not want this since we are controlling these packages.
Note: We should look at changing the name of our rpms to avoid this altogether since the al2/yum provided versions are really not upgrades to ours.

Ignore golang packages when checking for sec updates

---

eks-distro-base/Dockerfile.minimal-base-glibc

I noticed recently that the image builds are segfaulting a lot more than they used to.  This ends up being ok because the code falls back to objdump and ends up producing the same output.  I debugged this and realized that it was due to a mismatch in glibc version between the builder image and final image.  Since the current glibc build does not update the builder image at all, it is going to always have the version of glibc from when the previous minimal-base image was built, which could be months due to the few number of packages in that image.  When the final image is built it is always going to get the latest version of glibc from yum.
Later in the build process when the code uses ldd to find missing required libs, ldd would segfault …

Ensure glibc stays in sync between builder and final

---

eks-distro-base/Dockerfile.minimal-base-compiler

Our first golang consumer needed make in the golang compiler image.  We had them use the -gcc variant since it includes make, however, adding make to the compiler-base only adds like 1Mb.  It seems worth it to just move it up to the base so its in all the compiler variants.

Adds make to compiler-base

---

builder-base/scripts/install_final.sh

This seems to help avoid the checksum issue when running yum in fargate on builder-base

Adds yum-plugin-ovl to builder base

---

eks-distro-base/Dockerfile.minimal-base-golang
eks-distro-base/check_update.sh
eks-distro-base/scripts/install_golang

We arent uses these images as the build container for golang builds any more and so no longer need these packages in the rpm db.  I think we may want to do this at some point, but as is its kind of confusing because the names are the same as the upstream yum packages.  This means that if you ran yum check-update it would think our packages should be upgraded by the al2 provided package, which is not really our intent.

Stops including golang packages in rpm db

---

builder-base/Makefile
builder-base/update_base_image.sh
pr-scripts/update_image_tag.sh

There are a few jobs now using the minimal builder base. This changes the sed to only update the tag hash not the prefix of standard/minimal.

Avoid replacing minimal with standard for builder-base tag update

---

projects/golang/go/Makefile

Condition the image-build on AMD64 architecture. We don't want/need to be building + pushing an ARM64 image at this time; if we need to in the future, we can figure out the approach --either coordinating the builds so the manifest points to the right arch, or else pushing 2 tags.

EKS Go: condition image build + push on AMD64 arch

---

builder-base/update_base_image.sh

In my last [change](https://github.com/aws/eks-distro-build-tooling/pull/684) I missed that the BUILDER_BASE_TAG_FILE needed the standard/minimal prefix as well. We could harcode standard here, but this feels better just in case we change to minimal in the future, one less spot to change.

Handle variant prefix in builder_base_tag_file

---

helm-charts/stable/prow-control-plane/Chart.yaml
helm-charts/stable/prow-control-plane/values.yaml

Adding a new entrypoint script for a disk usage monitor sidecar to make it easier to track our usage esp on fargate nodes where it can be so critical.

Adds disk-usage cm to prow cp

---

eks-distro-base/Dockerfile.base

The daily image build has been building the 2022 images for a few days now when it shouldnt have, [example](https://github.com/aws/eks-distro-build-tooling/pull/688).
The check update code was properly detecting that there were new updates available, but the newly built image wasnt actually getting the latest packages. The reason for this was the way it checked for new `releasever`, which is new in al22 vs al2, they changed the output from `dnf update ...` to `dnf upgrade ...` so our grep was no longer matching.
They now provide a `latest` releasever so we can remove most of the existing logic and just always set to latest during the build.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Fixes al2022 distro base periodic build

---

eks-distro-base/Dockerfile.base
eks-distro-base/Dockerfile.minimal-base

In the al22 world yum is separated out to releasevers so by default when you run yum it will only pull the latest package for the current releasever. This is different than al2 which always pulls the actually latest when running yum install.  We handle this during the check-update phase, however when the images are actually built its not able to get the latest package since the releasever is never updated.
Setting the releasever file to latest appears to persist it for future runs which would mean that during any build process it will recheck for newer releasevers and use that to determine which yum packages to download/install.  Ill watch this as we get more builds. 
As a side note, we used to always rebuild all al22 images whenever …

Sets releasever to latest for al22 distro base images

---

projects/golang/go/docker/debianBase/Dockerfile

I expected the go archive to be added to `/usr/local/go` but it's currently not.
```
docker run -it public.ecr.aws/eks-distro-build-tooling/golang-debian:go1.19.4-1 /bin/bash
root@fb2bdc9d204f:/go# ls /usr/local/go
ls: cannot access '/usr/local/go': No such file or directory
```
Instead, it's added to `/usr/local`
```
docker run -it public.ecr.aws/eks-distro-build-tooling/golang-debian:go1.19.4-1 /bin/bash 
root@27bf04ae2de9:/go# ls /usr/local/bin/
go  gofmt  linux_amd64
root@27bf04ae2de9:/go# 
```
*Description of changes:* Go archive should be added to `/usr/local/go` instead of `/usr/local`. 

Add golang archive to /usr/local/go instead of /usr/local

---

projects/golang/go/1.16/patches/0020-go-1.16.15-eks-syscall-os-exec-reject-environ.patch
projects/golang/go/Makefile

Our patch for CVE-2022-41716 against Go v1.16.15 was broken by the erroneous inclusion of an intermediate commit. This was not detected as windows functionality was not exercised during the compilation process and standard unit tests, and no checks were in place for windows functionality.
I've re-built and tested the patch; additionally, I've added `std` install for multiple GOOS/GOARCH combos in order to act as a smoke-test against this kind of issue in the future.

Fix EKS Go 1.16.15 CVE-2022-41716 patch; add standard lib install as smoke test

---

builder-base/update_base_image.sh

Without the dash, the entirety of the tag was being selected for regex grouping, which caused an incorrect substitution.

Fix tag update logic for EKS-A Prowjobs

---

projects/golang/go/Makefile

adding `darwin/arm64` std lib install smoketest to EKS Go makefile

add darwin/arm64 platform to std lib install of eks go make

---

pr-scripts/create_pr.sh
pr-scripts/open_pr_check.sh

Follow up to: https://github.com/aws/eks-distro-build-tooling/pull/709
The open-pr check was a bit naive and since the string `al2` is included in the string `al22` the open pr code would bail out if there was a PR open against the al22 branch even tho it was looking for one open against the al2 branch.  This change uses the gh cli to find a PR for the specific branch instead of using grep against all open PRs.

Fixes open pr check for distro-base

---

pr-scripts/create_pr.sh

[Adding the 'do-not-merge/hold' label with the gh api ](https://github.com/aws/eks-distro-build-tooling/blob/main/pr-scripts/create_pr.sh#L128)doesn't work as the PR bot is not listed as an outside collaborator to our org (and just treated like an external developer). We could get around adding the bot by using a GH Action Labeler to hold all PRs from the bot, but even simpler is to use our existing Prow chatops feature with the slash hold command. 
Tested manually by adding the slash as the bot and it succceeded in adding hte label.

Trigger label with slash command

---

.gitignore
builder-base/Dockerfile
builder-base/Makefile
builder-base/scripts/download_golang.sh
builder-base/scripts/install_golang.sh

https://github.com/aws/eks-distro-internal/issues/308
We want to have fine-grained control over which Golang RPMs are installed on the `builder-base` at build time. Such controll will allow us to build and test a `builder-base` containing development Golang RPMs more easily.
This PR updates the `builder-base` Dockerfile Go install routine to simply `ADD` the Golang RPMs from the local context, rather than downloading them from the EKS-D CDN directly. The sourcing of the Golang RPMs is left to the Makefile. This will allow us to source the RPMs differently -- such as from the build artifacts of a pipeline, or another local build process, rather than locking us in to using the prod artifacts every time (as is the case with the …

decouple golang RPM download from `builder-base` Dockerfile

---

eks-distro-base/Makefile

Should fix periodic build when both al2 and al22 are running.

Only builds windows images during al2 build of distro base images

---

eks-distro-base/update_base_image_other_repos.sh

We got our first windows base image update yesterday. The code used to update the tag files in other repos, like eks-distro, was only looking at the al2 block of https://github.com/aws/eks-distro-build-tooling/pull/768. This fixes this to look at both al2 and windows. 
Once this is merged, i am going to rerun https://prow.eks.amazonaws.com/view/s3/prowdataclusterstack-316434458-prowbucket7c73355c-1n9f9v93wpjcm/logs/eks-distro-base-tag-files-update-postsubmit/1613510023281905664 to ensure it properly opens the PR in eks-distro.

Fixes update windows base image tag files in other repos

---

builder-base/scripts/install_go_licenses.sh

For background on the issue: https://github.com/google/go-licenses/pull/178
Tested in eks-a, updates made https://github.com/aws/eks-anywhere-build-tooling/pull/1718
I am going to work to get the PR upstream merged after doing verification with our build pipelines, which is mostly already done at this point, this is the last step.  For now, going to install go-liceses via my fork and will update back to the upstream tag when its available.

Bumps go-licenses to fix missing licenses bug

---

eks-distro-base/scripts/eks-d-common

We noticed that images based on AL22 which install yum in the final image (git/kind/compiler) were building over and over. This was due to the releasever not being set to latest so even tho the image was trigger to rebuild each day, it was still downloading the previous version of certain packages because the releasever was old. I tried to fix this in #712 but it appears that once the /newroot folder actually has yum installed, yum ignores the releasever file created in /etc.  
This PR replicates the releasever config file into the newroot folder as well as /etc.

Fixes al22 images with yum wrt releasever latest

---

builder-base/scripts/download_golang.sh
projects/golang/go/Makefile

*Description of changes:* [Explanation](https://quip-amazon.com/SEFsAzSpzdxB/Resolve-Noarch-RPM-Build-Sync-Path) As the part of the change, in this PR only the Makefile sync path will be changed. The `download_golang.sh` script pulls from the S3 bucket, thus if the Makefile change and the `download_golang.sh` scripts are changed in the same PR, the download_golang.sh script will try to pull from a path which doesn't exist yet. 
Also, in this PR a new target `clean` is introduced to free space before the `local-images` target is run.

Change RPM build sync destination for AMD and ARM architecture

---

tools/eksDistroBuildToolingOpsTools/docker/Dockerfile

Apparently ARG isn't available at the time ENTRYPOINT is run, which is why it was taking the literal $BINARY_NAME , but ENV is. If we want to leave it generic (just something discussed when writing the file originally) this was an option I found that is supposed to work.

Add env of the ARG binary name

---

tools/eksDistroBuildToolingOpsTools/docker/Dockerfile

Doing it the previous way invokes `/bin/sh -c echo $variable` which just returns the value at the variable which isn't the intended purpose. To try and test it as is, just going to hardcode for now and see if there is a good way to make generic later.

remove variable entrypoint

---

tools/eksDistroBuildToolingOpsTools/docker/Dockerfile

Output logs from the ops tool failing from `\"git\": executable file not found in $PATH",`

Add git image for ops tool

---

helm-charts/stable/prow-control-plane/templates/eksdistroopstool-Deployment.yaml
helm-charts/stable/prow-control-plane/templates/eksdistroopstool-Service.yaml
helm-charts/stable/prow-control-plane/values.yaml

Added the Deployment and Service values that are pulled when adding the tool to prod. Added the image information for the tool in the public ecr.
Tested the tool against personal repo and got expected responses to opened issues.

Add Ops Tool to PROD for Distro-build-tooling

---

projects/kubernetes/test-infra/Makefile

Adding Prow cherrypicker image to ECR public image mirror workflow.

Add Prow cherrypicker image to ECR public image mirror workflow

---

tools/eksDistroBuildToolingOpsTools/pkg/server/backportRequest.go
tools/eksDistroBuildToolingOpsTools/pkg/server/server.go

Add a /backport handler to the prow plugin, currently for go, but should be able to work for other projects as well.

Add backport request handler

---

tools/eksDistroBuildToolingOpsTools/Makefile
tools/eksDistroBuildToolingOpsTools/pkg/dependencyUpdater/etcd.go
tools/eksDistroBuildToolingOpsTools/pkg/dependencyUpdater/factory.go
tools/eksDistroBuildToolingOpsTools/pkg/dependencyUpdater/types.go

Adds a `dependencyUpdater` interface and example for implementing 'downstream automation', and providing a potential home for automation around tracking project updates

add dependnecy updater interfaces and framework

---

projects/golang/go/1.17/patches/0006-go-1.17.13-eks-net-http-update-bundled-golang.patch
projects/golang/go/1.17/patches/0007-go-1.17.13-eks-replace-all-usages-of-BytesOrPanic.patch
projects/golang/go/1.17/patches/0008-go-1.17.13-eks-multipart-limit-memory-inode-consumption.patch
projects/golang/go/1.17/patches/0009-go-1.17.13-eks-path-filepath-do-not-clean-relative-path.patch
projects/golang/go/1.17/patches/0010-go-1.17.13-eks-update-bundled-golang-org.patch
projects/golang/go/1.17/patches/0011-go-1.17.13-eks-net-http-update-bundled-golang.patch
projects/golang/go/1.17/rpmbuild/SPECS/golang.spec

https://github.com/aws/eks-distro-build-tooling/issues/880
Add patch for CVE-2022-27664 to Golang 1.17; clean up other patch formatting

Patch EKS Go 1.17 for CVE-2022-27664

---

projects/golang/go/Makefile
projects/golang/go/docker/debianBase/README.md
projects/golang/go/scripts/prow_release.sh

https://github.com/orgs/aws/projects/23/views/26?pane=issue&itemId=18822067
Now, when we release a Golang Debian Base Image, the tags will:
- include one tagged simply with the latest Git tag for the given version, with no other identifiers, to act like a 'latest' image
- include a tag which includes the Git tag, the EKS Go release number, and the Dockerfile release number
The Debian dockerfile release will also take place as a part of the standard EKS Go prod release. This way, we can still update the Dockerfile independently of the EKS Go release process in order to trigger a release and modify the image, but we also get the convenience of automation release when we release a new prod version of EKS Go. See the ticket for the whole …

unifiy golang and debian base image prod releases

---

EKS_DISTRO_TAG_FILE.yaml
eks-distro-base/Dockerfile.minimal-base-iptables
eks-distro-base/IPTABLES_WRAPPER_UPSTREAM.md
eks-distro-base/iptables-wrappers/LICENSE
eks-distro-base/iptables-wrappers/Makefile
eks-distro-base/iptables-wrappers/go.mod
eks-distro-base/iptables-wrappers/internal/commands/run.go
eks-distro-base/iptables-wrappers/internal/files/exist.go
eks-distro-base/iptables-wrappers/internal/iptables/alternatives.go
eks-distro-base/iptables-wrappers/internal/iptables/detect.go
eks-distro-base/iptables-wrappers/internal/iptables/rules.go
eks-distro-base/iptables-wrappers/internal/iptables/xtables.go
eks-distro-base/iptables-wrappers/main.go
eks-distro-base/iptables-wrappers/test/Dockerfile.test-alpine
eks-distro-base/iptables-wrappers/test/Dockerfile.test-debian
eks-distro-base/iptables-wrappers/test/Dockerfile.test-distroless
eks-distro-base/iptables-wrappers/test/Dockerfile.test-fedora
eks-distro-base/iptables-wrappers/test/build/clean-distroless.sh
eks-distro-base/iptables-wrappers/test/build/package-utils.sh
eks-distro-base/iptables-wrappers/test/build/stage-binaries-from-package.sh
eks-distro-base/iptables-wrappers/test/build/stage-binary-and-deps.sh
eks-distro-base/iptables-wrappers/test/run-test.sh
eks-distro-base/iptables-wrappers/test/wrapper_test.go
eks-distro-base/tests/Dockerfile
eks-distro-base/tests/run_tests.sh

This should resolve https://github.com/aws/eks-distro/issues/1729.
@g-gaston has been working with [upstream](https://github.com/kubernetes-sigs/iptables-wrappers/pull/6) on a golang based iptables-wrapper which we could use in our minimal images to properly switch the kube-proxy image from iptables-legacy to iptables-nft.  This PR pulls in the current state of this PR, which based on our testing seems pretty solid. This code is also very simple and easy enough to reason about that I feel comfortable getting a bit ahead here, esp considering our kube-proxy image does not work properly on hosts with iptables-nft as the default.
I have chosen to add the wrapper to the minimal iptables images, vs adding in the eks-d build so that we can …

Adds iptables-wrapper to iptables minimal image

---

builder-base/scripts/install_bash.sh

Remnant of the AL22 change to AL23 that needed to be updated. Following https://github.com/aws/eks-distro-build-tooling/pull/913 changes.

Remove IS_AL22 in install_bash

---

tools/eksDistroBuildToolingOpsTools/pkg/externalplugin/golangPatchReleaseRequest.go

We have previously been getting [this](https://github.com/aws/eks-distro-build-tooling/issues/887#issuecomment-1458525123) comment from the prow plugging. This change corrects the check to allow this.

Fix bot check in prow plugin

---

projects/golang/go/1.18/patches/0005-go-1.18.10-eks-go-scanner-reject-large-line-a.patch
projects/golang/go/1.18/patches/0006-go-1.18.10-eks-go-net-textproto-avoid-overpredic.patch
projects/golang/go/1.18/patches/0007-go-1.18.10-eks-mime-multipart-avoid-excessive.patch
projects/golang/go/1.18/patches/0008-go-1.18.10-eks-net-textproto-mime-multipart-i.patch
projects/golang/go/1.18/patches/0009-go-1.18.10-eks-mime-multipart-limit-parsed-mi.patch
projects/golang/go/1.18/rpmbuild/SPECS/golang.spec

Backport Go 1.19.8 CVE fixes to 1.18

---

projects/golang/go/1.16/patches/0030-go1.16.15-eks-go-scanner-reject-large-line-a.patch
projects/golang/go/1.16/patches/0031-go1.16.15-eks-mime-multipart-avoid-excessive.patch
projects/golang/go/1.16/patches/0032-go1.16.15-eks-net-textproto-mime-multipart-i.patch
projects/golang/go/1.16/patches/0033-go1.16.15-eks-mime-multipart-limit-parsed-mi.patch
projects/golang/go/1.16/patches/0034-go1.16.15-eks-net-textproto-avoid-overpredic.patch
projects/golang/go/1.16/patches/0105-add-Cut-method-to-bytes-package.patch
projects/golang/go/1.16/rpmbuild/SPECS/golang.spec

Backport Go 1.19.8 CVE fixes to 1.16

---

projects/golang/go/1.15/patches/0029-go-1.15.15-eks-go-scanner-reject-large-line-a.patch
projects/golang/go/1.15/patches/0030-go1.15.15-eks-mime-multipart-avoid-excessive.patch
projects/golang/go/1.15/patches/0031-go1.15.15-eks-net-textproto-mime-multipart-i.patch
projects/golang/go/1.15/patches/0032-go-1.15.15-eks-mime-multipart-limit-parsed-mi.patch
projects/golang/go/1.15/patches/0033-go1.15.15-eks-net-textproto-avoid-overpredic.patch
projects/golang/go/1.15/patches/0105-add-Cut-method-to-bytes-package.patch
projects/golang/go/1.15/rpmbuild/SPECS/golang.spec

Backport Go 1.19.8 CVE fixes to 1.15

---

eks-distro-base/update_base_image_other_repos.sh

I broke this a while ago.  The build was failing to check the other repo because the directory was missing the script_root prefix, since it was being used before it was set. this was the error in prow:
`fatal: cannot change to '/../../../eks-distro-pr-bot/eks-distro': No such file or directory`
I *think* this should bring back the updated packages sections in the PRs we open when bumping new base images.

fixes PR description to include updated packages in minimal images

---

EKS_DISTRO_TAG_FILE.yaml
eks-distro-base/Dockerfile.minimal-base-iptables
eks-distro-base/tests/Dockerfile

We added the golang based [iptables-wrapper ](https://github.com/kubernetes-sigs/iptables-wrappers/blob/master/main.go)script to the minimal iptables image a few months ago. At the time we decided to leave the default "alternative" as iptables-legacy to avoid casually breaking downstream consumers of this image.  At the time we updated eks-distro's [kube-proxy](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/release/docker/kube-proxy-base/Dockerfile) to use the new wrapper.
We are now ready to make the wrapper the default alternative to make it easier for downstream consumers to build their images to rely on this wrapper to properly flip between legacy/nft iptables mode based on the host OS.
*Notes*
After this merges and …

changes iptables minimal image default to use iptables-wrapper

---

helm-charts/patches/prow-control-plane/0001-EKS-D-changes-to-helm-control-plane-chart.patch
helm-charts/stable/prow-control-plane/Chart.yaml

*Issue #, if available:* N/A
https://github.com/aws/eks-distro-build-tooling/commit/6ebc3ad27c19251d494eb8f528239222a032a517 added some indenting to the crier RoleBinding which causes 'unknown field "subjects" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta,'
Before:
```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: crier
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: crier
subjects:
- kind: ServiceAccount
name: crier
namespace: {{ .Release.Namespace }}
```
After:
```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: crier
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: crier
subjects:
- kind: ServiceAccount
name: crier
namespace: {{ .Release.Namespace }}
```
By submitting this …

Fix crier RoleBinding

---

projects/golang/go/1.18/patches/0017-go-1.18.10-eks-net-http-validate-Host-header.patch
projects/golang/go/1.18/rpmbuild/SPECS/golang.spec

*Issue #, if available:* backport the fix from 1.19.11 to 1.18.10 https://github.com/aws/eks-distro-build-tooling/issues/1056 
cherry picked https://github.com/golang/go/commit/5fa6923b1ea891400153d04ddf1545e23b40041b from release-branch.go1.19
Technically there was a merge conflict due to gofmt having been applied on go 1.19, see https://github.com/golang/go/blame/3d33532d1cb25955d2bb236394a0afa99899a35c/src/net/http/request.go#L751-L755 vs https://github.com/golang/go/blame/release-branch.go1.18/src/net/http/request.go#L739-L741C55, that's why this patch changes 45 lines whereas the 1.19 changes 47, but I am not sure it was worth mentioning in the commit header.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Add go1.18.10 patch 'validate Host header before sending'

---

EKS_DISTRO_TAG_FILE.yaml

*Issue #, if available:* https://github.com/aws/eks-distro-build-tooling/issues/1056
*Description of changes:* trigger iptables build with new go version
/hold

null iptables image tags

---

helm-charts/stable/prow-data-plane/Chart.yaml
helm-charts/stable/prow-data-plane/templates/prow-controller-manager-Role.yaml

Prow control plane failing to update prowjobs in beta
**Fix**
The addition of this [check](https://github.com/kubernetes/test-infra/commit/de4a80675caca4dc9433b21aaadf92e98f29fed1) in the prow image and the requirement to update prow images to for the [Github RSA public key](https://github.com/aws/eks-distro-build-tooling/pull/997). We need to add the `get` action to the prow controller manager, in the data plane clusters. These checks cause the manager to fail on creation
```
requiredTestPodVerbs := []string{
"create",
"delete",
"list",
"watch",
"get",
"patch",
}
```
**Testing**
Discovery of this required several steps, when viewing the logs `kubectl logs <prow-controller-manager pod>` there was this entry 
```
{...,"error":"[failed pod …
```

Add get to allowed actions for prow controller manager

---

release/pkg/kube_reader.go

our release code is choking on the RC git tag; not exactly sure where the `+` in the string is getting added, as it's part of the generated KUBE_VERSION_FILE that is generated for communication of kube version information among the release code, but added some prints in there to try and get more info and a simple hack to get around it for now.

add some printlns and a hack to get around errors in 1.28 release

---

projects/golang/go/1.18/patches/0018-go-1.18.10-eks-crypto-tls-restrict-RSA-keys-i.patch
projects/golang/go/1.18/rpmbuild/SPECS/golang.spec

Backport patch to address CVE-2023-29409 to EKS Golang `v1.18`.

add patch for CVE-2023-29409 in Golang 1.18

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/install-CronJob.yaml

Getting warnings about k8 1.22+ deprecating the cronjob v1beta1 api -> v1. Bumping the helm version to include the change.

Update cron job api version due to K8s deprecation

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/config/install.sh
helm-charts/stable/amazon-eks-pod-identity-webhook/config/uninstall.sh

Updating the kubelet version for pod-identity-webhook and bumping the chart version

Update kubectl version for amazon-eks-pod-identity-webhook

---

projects/golang/go/scripts/eks_golang_release_notification.sh

Adding the `--profile` flag to use the profile when calling `aws sns` for golang release.

Add profile flag for Golang sns script

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/config/mutatingwebhook.yaml

Update the values for the mutating webhook following the [deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#webhook-resources-v122)

Update mutating webhook due to v1beta1 deprecation

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/_helpers.tpl

No definition in helper for "amazon-eks-pod-identity-webhook.secretName"

Include helper for cert name

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Deployment.yaml

When attempting deployment I am receiving `parse error on amazon-eks-pod-identity-webhook/templates/Deployment.yaml: error converting YAML to JSON: yaml: line 10: could not find expected \':\'\n'`
This was the recommended fix by https://github.com/helm/helm/issues/2004

Change indent pattern in pod-identity-webook Deployment.yaml

---

EKS_DISTRO_TAG_FILE.yaml

Revert https://github.com/aws/eks-distro-build-tooling/pull/1165

Restore eks-distro-minimal-base-iptables value

---

projects/golang/go/1.21/rpmbuild/SPECS/golang.spec

update Go 1.21 spec to include the go.env in the go root during the build. Thx @jaxesn 
https://src.fedoraproject.org/rpms/golang/c/e1a400ab5f64e0883f3516f49f8d7e25dcdd9449?branch=rawhide

Update golang spec to include go env

---

projects/golang/go/VulnerabilityManagement/eks-distro-golang-vex.json

Initial commit adding a baisc VEX (vulnerability eXchange) document for EKS Go (see https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/prose/csaf-v2-editor-draft.md). We can use this to track what CVEs are fixed where and then filter them out of GoVulnCheck etc
Only have one CVE in here right now will add more once this is looking good

initial commit for EKS Go vulnerability management tracking

---

projects/golang/go/VulnerabilityManagement/eks-distro-golang-vex.json

add additional 1.18 and 1.19 CVEs to VEX document for testing

Add additional CVE entries to VEX document

---

generate-attribution/generate-attribution-file.js
generate-attribution/package-lock.json
generate-attribution/package.json
generate-attribution/tests/cases/containernetworking/plugins/ATTRIBUTION.txt
generate-attribution/tests/cases/coredns/coredns/ATTRIBUTION.txt
generate-attribution/tests/cases/etcd-io/etcd/ATTRIBUTION.txt
generate-attribution/tests/cases/fluxcd/source-controller/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes-csi/external-attacher/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes-csi/external-provisioner/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes-csi/external-resizer/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes-csi/external-snapshotter/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes-csi/livenessprobe/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes-csi/node-driver-registrar/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes-sigs/aws-iam-authenticator/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes-sigs/cri-tools/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes-sigs/metrics-server/ATTRIBUTION.txt
generate-attribution/tests/cases/kubernetes/kubernetes-1-19/ATTRIBUTION.txt

We will occasionally see timeouts when requesting the go-import url.  This code has largely been unchanged for 2 years, but turns out the retry logic was just wrong and when the timeouts would occur, they would sometimes result in uncaught exceptions.  This looks like a big change, but for the most part its just changing the old promise still methods to better utilize async/await and actually work in terms of retrying.
Since I was here, went ahead and updated the dependencies and updated some of the expected output files due to changes in upstream repo names.

fixes attribution retry logic

---

builder-base/Dockerfile
builder-base/scripts/install_final.sh

This is something the eks-a image builder requires which has for all this time been downloaded at build time.  This upstream endpoint will go down from time to time, breaking builds unnecessarily. Baking these in will help with stability.

adds ansible collections needed for image builds

---

builder-base/Dockerfile
builder-base/Makefile
builder-base/scripts/install_ansible.sh
builder-base/scripts/install_final.sh
builder-base/scripts/validate_components.sh

My first attempt at adding python3.9 to the al2 builder base was bad. It was copying the entire minimal python image root over top the builder base root. This seemed fine in theory, but since the builder rebuilds bash from source this copy was replacing the built bash 4.3 with the older 4.2. This causes issues in certain builds that require 4.3+.
This new approach targets the specific python bins/libs that we need instead of the whole root.

improves python 3.9 on al2 builder base

---

eks-distro-base/update_base_image_other_repos.sh
pr-scripts/create_pr.sh

Originally when PRs were opened like [this](https://github.com/aws/eks-anywhere-build-tooling/pull/2634) within the PR body the packages in the image which changed were included.  This code all still mostly exists, but at some point we broke it due to preparing the PR body in a file and reading the file in, overwriting the variable after we added the extra bit of body text.
I also tweaked the loop which creates these PRs so that the PR bodies only include the changes for the images which are used in that repo.

fixes PR body when opening PRs in other repos for minimal images

---

tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/githubRelease.go
tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/versionReadmeFmt.txt

The logic for bumping releases needed to account for `\n`, but also had to account for larger releases. Revert the PR open repo to be `aws`

Correct a few issues with the golang tooling

---

tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/createPatch.go
tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/githubRelease.go
tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/newVersion.go
tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/release.go
tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/updateRelease.go
tools/eksDistroBuildToolingOpsTools/pkg/prManager/prManager.go

Add `commitBranch` variable to ensure the correct branch is used to open update prs vs release prs.

Add commitBranch variable to avoid duplicate prs

---

builder-base/scripts/install_golang.sh

After releasing the new builder base when we added the upx compression for a number of the larger executables within this image, we started seeing a couple out of memory exceptions when building a couple of the eks-a components.  We do these builds on small (1cpu 4gb) arm instances in codebuild.  For the time being we bumped those to large and the problem went away.
I think based on the upx docx, which i quoted inline here for reference, since the compile command, and i *think* the link command, are usually running multiple instances, it makes sense that we are seeing this increase in RAM requirement which is triggering a OOM exception in our builds.
I have take this approach to just exclude the 2 we are pretty sure are the culprits.  We …

skips go link and compile when running upx

---

projects/kubernetes/kops/kops_artifacts_management_tools.sh

Artifacts for `darwin` don't exist making local runs of kOps not work

Update supported version of kOps

---

release/pkg/kube_reader.go

Add the filtering of `+` values in minor version release candidates. This failed and required reverting last time due to additional println which made their way into the yaml files. This shouldn't be the case here, but we can watch for this as a previously known issue.
https://github.com/aws/eks-distro-build-tooling/pull/1095 

Restore filtering + from release candidate k8s versions

---

builder-base/scripts/install_notation.sh

Add AWS Signer plugin binary for notation CLI.
Download link - https://docs.aws.amazon.com/signer/latest/developerguide/image-signing-prerequisites.html
Followed steps:
Configure AWS Signer Plugin
1. Download latest binary from the link mentioned on above the aws doc site.
2. Copy the binary  to notation plugin location
- For linux the location is  $HOME/.config/notation/plugins/com.amazonaws.signer.notation.plugin
3. Give execute permission to the plugin
4. Remove downloaded zip folder and other files extracted with that.

Add aws signer plugin for notation in the builder base

---

tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/release.go
tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/updateRelease.go

When using the `eksGoRelease` commands, readme update makes more sense when officially [releasing the new version](https://github.com/aws/eks-distro-build-tooling/pull/1279/files) rather than [adding the patches and other changes](https://github.com/aws/eks-distro-build-tooling/pull/1273/files).

Switch eks go readme update to occur on release

---

.github/workflows/kopsRelease.yaml

Found [this workflow](https://github.com/vmware-tanzu/sonobuoy/blob/main/.github/workflows/k8sRelease.yaml) for monitoring projects for releases. Wanted to try it out here since we require a new release of kops

add workflow step to create issue on new kOps releases

---

builder-base/scripts/install_hugo.sh

Fixing the Hugo ARM64 GitHub release tarball name.

Fix Hugo tarball name for ARM64

---

helm-charts/stable/amazon-eks-pod-identity-webhook/Chart.yaml
helm-charts/stable/amazon-eks-pod-identity-webhook/templates/Deployment.yaml

This error is fixed by adding `-`, had issues with parsing the parameterized values so just hardcoding for the time being.
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: Val
idationError(Certificate.spec.dnsNames): invalid type for io.cert-manager.v1.Certificate.spec.dnsNames: got "string", expected "array"
```
Newly produced template:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
name: eks-distro-pod-identity-webhook
namespace: default
spec:
secretName: eks-distro-pod-identity-webhook-cert 
commonName: "pod-identity-webhook.default.svc"
dnsNames:
- "eks-distro-pod-identity-webhook"
- "eks-distro-pod-identity-webhook.default"
- …
```

Fix failing helmchart 

---

tools/eksDistroBuildToolingOpsTools/cmd/eksGoRelease/README.md

Update eksGoRelease readme guide

---

tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease/githubRelease.go

Handle creation of RELEASE file in new Go version Release
When we run
```
./eksGoRelease release --eksGoReleases=1.22.0 -e jasondu31.coding@gmail.com -u xdu31
```
It errors out with the follow error:
```
finding filename	{"filename": "projects/golang/go/1.22/RELEASE", "error": "file not found"}
Reading file	{"file": "projects/golang/go/1.22/RELEASE", "error": "file not found"}
increment release	{"error": "file not found"}
Error: you have failed this automation: file not found
```
This happens when it is a new Go version release

Handle creation of RELEASE file in new Go version Release

---

EKS_DISTRO_TAG_FILE.yaml

Trigger Builder-Base update for Go 1.20.14, 1.21.7, 1.22.0

Trigger Builder-Base update for Go 1.20.14, 1.21.7, 1.22.0

---

tools/eksDistroBuildToolingOpsTools/cmd/eksGoRelease/cmd/root.go

*Issue #, if available:* n/a
*Description of changes:* it is required for each command, require it instead of silently exiting when it is not provided

Mark --eksGoReleases required for eksGoRelease

---

OWNERS

remove EKS-A folks from owners

Remove EKS-A folks from OWNERS

---

builder-base/scripts/check_upstream_golang.sh
eks-distro-base/scripts/check_upstream_golang

updated scripts to set empty variables when unable to find the proper version. Updated eks-distro-base/scripts/check_upstream_golang.sh to use yq to find version information.
```
➜  eks-distro-build-tooling git:(fix-go-version) ✗ make check-golang-release -C eks-distro-base
/eks-distro-build-tooling/eks-distro-base/scripts/check_upstream_golang
+ GO_PREFIX=go
+++ dirname /eks-distro-build-tooling/eks-distro-base/scripts/check_upstream_golang
++ cd /eks-distro-build-tooling/eks-distro-base/scripts
++ pwd -P
+ SCRIPT_ROOT=/eks-distro-build-tooling/eks-distro-base/scripts
+ VERSIONS_YAML=/eks-distro-build-tooling/eks-distro-base/scripts/../golang_versions.yaml
++ curl 'https://go.dev/dl/?mode=json'
++ jq -r '.[].version'
++ sed -e 's/^go//' …
```

updated check_upstream_golang.sh to properly set empty variables

---

pr-scripts/create_pr.sh

The golang pr name expected the wrong Prowjob name for automation.
From prowjobs automation
```
...
job: check-upstream-golang-release
namespace: default
pod_spec:
...
```

Correct golang release automation prowjob name

---

eks-distro-base/Makefile

The period for checking for new releases of golang is failing due to the missing file `golang_versions.yaml` not existing in the local repo. 
```
+ git add ./eks-distro-base/golang_versions.yaml
fatal: pathspec './eks-distro-base/golang_versions.yaml' did not match any files
make: *** [create-golang-release-pr] Error 128
make: Leaving directory `/home/prow/go/src/github.com/aws/eks-distro-build-tooling/eks-distro-base'
```
There is an additional make target [open-pr-check](https://github.com/aws/eks-distro-build-tooling/blob/a843551b08db58b336d44bdeef3c883c68b73497/eks-distro-base/Makefile#L450) that needs to be called similarly to the `make update` call: https://github.com/aws/eks-distro-build-tooling/blob/a843551b08db58b336d44bdeef3c883c …

Fix check golang

---

projects/golang/go/Makefile
projects/golang/go/docker/debianBase/Dockerfile
projects/golang/go/scripts/get_upstream_golang.sh
projects/golang/go/scripts/prow_release_images.sh

These changes were tested using the new `make local-images-upstream-bins` which is identical to the final call except `PUSH_IMAGES=false`. Both of these based of the make targets for building the current debian images with new variables and scripts used pulling upstream binaries instead of the EKS Go s3 images previously generated. 
Output from the `make local-images-upstream-bins` command calling the new `get_upstream_golang.sh`. This script checks the builder-base files for referencing which version of golang the debian images should use. From here the Makefile and Dockerfile create the relevant image using the tags. Using the existing postsubmits we can trigger off a merge of the `eks-distro-base/golang_versions.yaml` (this file should …

Add infrastructure for generating the golang-debian image using upstream binaries

---

builder-base/scripts/download_golang.sh
builder-base/scripts/update_shasums.sh
eks-distro-base/Makefile
pr-scripts/create_pr.sh

When running the periodic releasing new golang images, we should update the expected make tests files related to golang and the checksums files used for verifying the builder-base

Auto update golang checksums and expected make tests

---

builder-base/scripts/check_upstream_golang.sh

`gsed` was used for local testing. Need to use `sed` in the periodic.

Use sed instead of gsed in golang automation

---

pr-scripts/create_pr.sh

Make targets run against the base `aws/eks-distro-build-tooling` repo. Other make targets using the `create-pr` target 
sync the changes using other scripts. For time being we can copy the expected files during this periodic only not using a sync script. 

Cp files from main repo to fork during golang periodic

---

projects/golang/go/Makefile

update images-upstream-bins to use default env vars to fix image push

---

projects/golang/go/Makefile

update images-upstream-bins to use different tags

---

eks-distro-base/scripts/check_upstream_golang

use `minorversion` instead of `MINORVERSION` in `sed` command. `MINORVERSION` is used in yq and not being persisted as expected. `minorversion` should accomplish same thing and shows as set correctly in logs.

Fix new golang minor version release automation path

---

builder-base/Dockerfile

add go 1.23 image and license image to builder-base Dockerfile

---

eks-distro-base/README.md

*Issue #, if available:* N/A
*Description of changes:* Fixed some broken links and formatting in a header in README

Fixed Markdown in eks-distro-base/README.md

---

projects/kubernetes/test-infra/Makefile
projects/kubernetes/test-infra/docker/linux/deck/Dockerfile

Ensure correct Dockerfile is used for deck image builds

Ensure correct Dockerfile is used for deck image builds

---

projects/kubernetes/test-infra/Makefile

We need to build only AMD64 images for Prow components since the Prow controlplane cluster has only AMD64 nodes and we will not be adding any ARM64 nodes in the future.

Build only AMD64 images for Prow components

---

release/pkg/assets_snapshotter.go
release/pkg/generate_spec.go

Skipping to update the images. for mpvarma/update-checking-csi-snapshotter as this image is bumped but not published to the external repo. 
```
Error updating image digests: ImageNotFoundException: The image with imageId {imageDigest:'null', imageTag:'v8.2.0-eks-1-29-30'} does not exist within the repository with name 'kubernetes-csi/external-snapshotter/snapshot-validation-webhook' in the registry with id '316434458148'
```
https://prow.eks.amazonaws.com/view/s3/prowdataclusterstack-316434458-prowbucket7c73355c-1n9f9v93wpjcm/logs/dev-release-1-29-postsubmit/1869869112969138176#2:build-container-build-log.txt%3A8080
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Skipping the kubernetes-csi/external-snapshotter images to update

---

eks-distro-base/iptables-wrappers/go.mod

Bump go version for iptables-wrappers
Outdated go version is causing test coverage failures: https://github.com/aws/eks-distro-build-tooling/actions/runs/12286979132/job/34288142977?pr=1576
Bump to the go 1.23

Bump go version for iptables-wrappers to 1.23

---

.github/workflows/go-coverage.yml
.github/workflows/golangci-lint.yml

Bump outdated go version in the workflows
Bumped from 1.19 to 1.23 so that the latest dependencies can run.

Bump go versions in the workflows

---

eks-distro-base/README.md
eks-distro-base/update_base_image_other_repos.sh

After [this](https://github.com/aws/eks-anywhere-build-tooling/pull/4195) change in eks-anywhere-build-tooling, this automation is no longer required since the new images are polled for and updated.

Remove EKS-A build-tooling repository from tags automation

---

EKS_DISTRO_TAG_FILE.yaml

We have identified a CVE in kube-proxy, which uses the base image public.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base-iptables:latest-al23. To address this, we need to create a new image with an updated Go patch version.
Reproduce:
```
trivy image public.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base-iptables:latest-al23
trivy image public.ecr.aws/eks-distro/kubernetes/kube-proxy:v1.31.4-eks-1-31-latest
```

Trigger builder-base update for iptables

---

projects/kubernetes/kops/Makefile
projects/kubernetes/kops/patches/0002-Add-Kubernetes-1.33-compatibility-with-cloud-provide.patch

[Fix Unary issue](https://prowdataclusterstack-316434458-prowbucket7c73355c-1n9f9v93wpjcm.s3.us-west-2.amazonaws.com/logs/kops-tooling-postsubmit/1908305849818812416/build-container-build-log.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAUTLHWUYSIMZMDZZJ%2F20250405%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20250405T154044Z&X-Amz-Expires=600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjELj%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLXdlc3QtMiJIMEYCIQDrC4dGoek5ETFdOovxTjYlAALRvz0S9Bb7t9oInUYkcQIhAIGU%2Bm6uR2c%2Fc3aZl%2FZz%2Fye6VJWw7UIHINyjNyJ%2BploHKvAECDAQARoMMzE2NDM0NDU4MTQ4Igyo6WhkNKflNbqx8ZwqzQQut8lnzeHdCm9RWXQqZpWTjc4BBWW%2FsSjCcdWSLqSCZ0oFDfSNDW60wmc1rQPEq58Y%2ByWt7uhN08QYDPkzAqTYDbjcWfDeuy%2F1X%2FNzEd9e2sK4IKiedTsyWp5M95DG%2BQfC7fKbx710WzvaHBRTB8AiaAiADHm2U1wJ%2FPt06QJD%2FiJN2zbG75YfF91 …

Fix patch for multiple patch files + Add a custom patch file

---

release/pkg/assets_metricsserver.go

Use same metrics server as 1.32 for 1.33

---

EKS_DISTRO_TAG_FILE.yaml

We use this image as the base of the emissary image which also needs to install curl on top.  https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/emissary-ingress/emissary/docker/linux/emissary/Dockerfile#L10
This started failing recently due to errors like:
`/newroot/usr/bin/openssl: /newroot/lib64/libcrypto.so.3: version `OPENSSL_3.2.0'\'' not found (required by /newroot/usr/bin/openssl)` 
when trying to run ldd on the curl binary and other libraries. Im pretty sure this is due to changes in openssl version recently in al23, but we havent had a new python3.11 build since.  We the emissary build tries to install curl, its getting newer versions of the curl package which depend on the newwer openssl/crypto.
Forcing a new python 3.11 build *should* …

trigger a new python 3.11 al23 image

---

.github/workflows/base-image-pr-notifier.yml

- Move PR title to environment variable
- Maintains identical functionality

fix: prevent script injection in base-image-pr-notifier
